import type { JobInformationType } from '../migrations/00010-createtablejobinformation';

export const jobInformationDummyData: JobInformationType[] = [
  {
    id: 1,
    jobFunctionId: 4,
    seniorityId: 4,
    industryId: 6,
    genderId: 1,
    userId: 1,
    salary: 114000,
    yearsOfExperience: 11,
  },
  {
    id: 2,
    jobFunctionId: 2,
    seniorityId: 5,
    industryId: 4,
    genderId: 1,
    userId: 2,
    salary: 133000,
    yearsOfExperience: 18,
  },
  {
    id: 3,
    jobFunctionId: 4,
    seniorityId: 2,
    industryId: 1,
    genderId: 1,
    userId: 3,
    salary: 61750,
    yearsOfExperience: 4,
  },
  {
    id: 4,
    jobFunctionId: 5,
    seniorityId: 5,
    industryId: 6,
    genderId: 2,
    userId: 4,
    salary: 126000,
    yearsOfExperience: 15,
  },
  {
    id: 5,
    jobFunctionId: 4,
    seniorityId: 2,
    industryId: 6,
    genderId: 1,
    userId: 5,
    salary: 61750,
    yearsOfExperience: 6,
  },
  {
    id: 6,
    jobFunctionId: 5,
    seniorityId: 4,
    industryId: 6,
    genderId: 1,
    userId: 6,
    salary: 114000,
    yearsOfExperience: 12,
  },
  {
    id: 7,
    jobFunctionId: 1,
    seniorityId: 1,
    industryId: 6,
    genderId: 2,
    userId: 7,
    salary: 36750,
    yearsOfExperience: 2,
  },
  {
    id: 8,
    jobFunctionId: 3,
    seniorityId: 4,
    industryId: 3,
    genderId: 1,
    userId: 8,
    salary: 114000,
    yearsOfExperience: 13,
  },
  {
    id: 9,
    jobFunctionId: 6,
    seniorityId: 1,
    industryId: 2,
    genderId: 1,
    userId: 9,
    salary: 42750,
    yearsOfExperience: 1,
  },
  {
    id: 10,
    jobFunctionId: 4,
    seniorityId: 4,
    industryId: 3,
    genderId: 1,
    userId: 10,
    salary: 114000,
    yearsOfExperience: 13,
  },
  {
    id: 11,
    jobFunctionId: 5,
    seniorityId: 2,
    industryId: 2,
    genderId: 1,
    userId: 11,
    salary: 61750,
    yearsOfExperience: 4,
  },
  {
    id: 12,
    jobFunctionId: 5,
    seniorityId: 2,
    industryId: 2,
    genderId: 2,
    userId: 12,
    salary: 47250,
    yearsOfExperience: 6,
  },
  {
    id: 13,
    jobFunctionId: 3,
    seniorityId: 2,
    industryId: 1,
    genderId: 2,
    userId: 13,
    salary: 47250,
    yearsOfExperience: 4,
  },
  {
    id: 14,
    jobFunctionId: 3,
    seniorityId: 4,
    industryId: 3,
    genderId: 1,
    userId: 14,
    salary: 114000,
    yearsOfExperience: 13,
  },
  {
    id: 15,
    jobFunctionId: 6,
    seniorityId: 3,
    industryId: 6,
    genderId: 2,
    userId: 15,
    salary: 68250,
    yearsOfExperience: 7,
  },
  {
    id: 16,
    jobFunctionId: 5,
    seniorityId: 4,
    industryId: 1,
    genderId: 1,
    userId: 16,
    salary: 114000,
    yearsOfExperience: 14,
  },
  {
    id: 17,
    jobFunctionId: 1,
    seniorityId: 1,
    industryId: 2,
    genderId: 1,
    userId: 17,
    salary: 42750,
    yearsOfExperience: 1,
  },
  {
    id: 18,
    jobFunctionId: 2,
    seniorityId: 3,
    industryId: 6,
    genderId: 2,
    userId: 18,
    salary: 68250,
    yearsOfExperience: 7,
  },
  {
    id: 19,
    jobFunctionId: 3,
    seniorityId: 4,
    industryId: 5,
    genderId: 2,
    userId: 19,
    salary: 94500,
    yearsOfExperience: 13,
  },
  {
    id: 20,
    jobFunctionId: 6,
    seniorityId: 2,
    industryId: 3,
    genderId: 1,
    userId: 20,
    salary: 61750,
    yearsOfExperience: 6,
  },
  {
    id: 21,
    jobFunctionId: 2,
    seniorityId: 4,
    industryId: 5,
    genderId: 1,
    userId: 21,
    salary: 114000,
    yearsOfExperience: 11,
  },
  {
    id: 22,
    jobFunctionId: 6,
    seniorityId: 5,
    industryId: 5,
    genderId: 2,
    userId: 22,
    salary: 126000,
    yearsOfExperience: 15,
  },
  {
    id: 23,
    jobFunctionId: 2,
    seniorityId: 1,
    industryId: 1,
    genderId: 2,
    userId: 23,
    salary: 36750,
    yearsOfExperience: 3,
  },
  {
    id: 24,
    jobFunctionId: 1,
    seniorityId: 2,
    industryId: 3,
    genderId: 2,
    userId: 24,
    salary: 47250,
    yearsOfExperience: 4,
  },
  {
    id: 25,
    jobFunctionId: 5,
    seniorityId: 4,
    industryId: 6,
    genderId: 2,
    userId: 25,
    salary: 94500,
    yearsOfExperience: 13,
  },
  {
    id: 26,
    jobFunctionId: 2,
    seniorityId: 3,
    industryId: 4,
    genderId: 2,
    userId: 26,
    salary: 68250,
    yearsOfExperience: 10,
  },
  {
    id: 27,
    jobFunctionId: 1,
    seniorityId: 3,
    industryId: 3,
    genderId: 2,
    userId: 27,
    salary: 68250,
    yearsOfExperience: 7,
  },
  {
    id: 28,
    jobFunctionId: 6,
    seniorityId: 2,
    industryId: 6,
    genderId: 2,
    userId: 28,
    salary: 47250,
    yearsOfExperience: 4,
  },
  {
    id: 29,
    jobFunctionId: 5,
    seniorityId: 2,
    industryId: 1,
    genderId: 1,
    userId: 29,
    salary: 61750,
    yearsOfExperience: 6,
  },
  {
    id: 30,
    jobFunctionId: 4,
    seniorityId: 3,
    industryId: 1,
    genderId: 2,
    userId: 30,
    salary: 68250,
    yearsOfExperience: 10,
  },
  {
    id: 31,
    jobFunctionId: 2,
    seniorityId: 5,
    industryId: 4,
    genderId: 1,
    userId: 31,
    salary: 133000,
    yearsOfExperience: 15,
  },
  {
    id: 32,
    jobFunctionId: 4,
    seniorityId: 3,
    industryId: 3,
    genderId: 2,
    userId: 32,
    salary: 68250,
    yearsOfExperience: 9,
  },
  {
    id: 33,
    jobFunctionId: 1,
    seniorityId: 4,
    industryId: 3,
    genderId: 2,
    userId: 33,
    salary: 94500,
    yearsOfExperience: 12,
  },
  {
    id: 34,
    jobFunctionId: 4,
    seniorityId: 3,
    industryId: 5,
    genderId: 1,
    userId: 34,
    salary: 85500,
    yearsOfExperience: 10,
  },
  {
    id: 35,
    jobFunctionId: 5,
    seniorityId: 5,
    industryId: 5,
    genderId: 1,
    userId: 35,
    salary: 133000,
    yearsOfExperience: 18,
  },
  {
    id: 36,
    jobFunctionId: 5,
    seniorityId: 4,
    industryId: 5,
    genderId: 2,
    userId: 36,
    salary: 94500,
    yearsOfExperience: 10,
  },
  {
    id: 37,
    jobFunctionId: 5,
    seniorityId: 1,
    industryId: 6,
    genderId: 2,
    userId: 37,
    salary: 36750,
    yearsOfExperience: 2,
  },
  {
    id: 38,
    jobFunctionId: 2,
    seniorityId: 5,
    industryId: 5,
    genderId: 2,
    userId: 38,
    salary: 126000,
    yearsOfExperience: 18,
  },
  {
    id: 39,
    jobFunctionId: 3,
    seniorityId: 2,
    industryId: 3,
    genderId: 2,
    userId: 39,
    salary: 47250,
    yearsOfExperience: 6,
  },
  {
    id: 40,
    jobFunctionId: 5,
    seniorityId: 3,
    industryId: 6,
    genderId: 1,
    userId: 40,
    salary: 85500,
    yearsOfExperience: 10,
  },
  {
    id: 41,
    jobFunctionId: 4,
    seniorityId: 5,
    industryId: 4,
    genderId: 2,
    userId: 41,
    salary: 126000,
    yearsOfExperience: 17,
  },
  {
    id: 42,
    jobFunctionId: 1,
    seniorityId: 1,
    industryId: 5,
    genderId: 1,
    userId: 42,
    salary: 42750,
    yearsOfExperience: 3,
  },
  {
    id: 43,
    jobFunctionId: 5,
    seniorityId: 5,
    industryId: 2,
    genderId: 2,
    userId: 43,
    salary: 126000,
    yearsOfExperience: 19,
  },
  {
    id: 44,
    jobFunctionId: 4,
    seniorityId: 1,
    industryId: 2,
    genderId: 2,
    userId: 44,
    salary: 36750,
    yearsOfExperience: 3,
  },
  {
    id: 45,
    jobFunctionId: 5,
    seniorityId: 5,
    industryId: 1,
    genderId: 1,
    userId: 45,
    salary: 133000,
    yearsOfExperience: 17,
  },
  {
    id: 46,
    jobFunctionId: 3,
    seniorityId: 3,
    industryId: 4,
    genderId: 2,
    userId: 46,
    salary: 68250,
    yearsOfExperience: 8,
  },
  {
    id: 47,
    jobFunctionId: 1,
    seniorityId: 5,
    industryId: 6,
    genderId: 2,
    userId: 47,
    salary: 126000,
    yearsOfExperience: 17,
  },
  {
    id: 48,
    jobFunctionId: 5,
    seniorityId: 1,
    industryId: 3,
    genderId: 1,
    userId: 48,
    salary: 42750,
    yearsOfExperience: 1,
  },
  {
    id: 49,
    jobFunctionId: 4,
    seniorityId: 2,
    industryId: 5,
    genderId: 2,
    userId: 49,
    salary: 47250,
    yearsOfExperience: 5,
  },
  {
    id: 50,
    jobFunctionId: 2,
    seniorityId: 5,
    industryId: 5,
    genderId: 2,
    userId: 50,
    salary: 126000,
    yearsOfExperience: 20,
  },
  {
    id: 51,
    jobFunctionId: 4,
    seniorityId: 3,
    industryId: 5,
    genderId: 1,
    userId: 51,
    salary: 85500,
    yearsOfExperience: 10,
  },
  {
    id: 52,
    jobFunctionId: 3,
    seniorityId: 2,
    industryId: 6,
    genderId: 2,
    userId: 52,
    salary: 47250,
    yearsOfExperience: 5,
  },
  {
    id: 53,
    jobFunctionId: 6,
    seniorityId: 2,
    industryId: 1,
    genderId: 2,
    userId: 53,
    salary: 47250,
    yearsOfExperience: 5,
  },
  {
    id: 54,
    jobFunctionId: 1,
    seniorityId: 4,
    industryId: 5,
    genderId: 2,
    userId: 54,
    salary: 94500,
    yearsOfExperience: 13,
  },
  {
    id: 55,
    jobFunctionId: 6,
    seniorityId: 3,
    industryId: 3,
    genderId: 1,
    userId: 55,
    salary: 85500,
    yearsOfExperience: 8,
  },
  {
    id: 56,
    jobFunctionId: 1,
    seniorityId: 1,
    industryId: 4,
    genderId: 2,
    userId: 56,
    salary: 36750,
    yearsOfExperience: 2,
  },
  {
    id: 57,
    jobFunctionId: 6,
    seniorityId: 4,
    industryId: 3,
    genderId: 2,
    userId: 57,
    salary: 94500,
    yearsOfExperience: 10,
  },
  {
    id: 58,
    jobFunctionId: 2,
    seniorityId: 3,
    industryId: 2,
    genderId: 1,
    userId: 58,
    salary: 85500,
    yearsOfExperience: 9,
  },
  {
    id: 59,
    jobFunctionId: 2,
    seniorityId: 1,
    industryId: 2,
    genderId: 2,
    userId: 59,
    salary: 36750,
    yearsOfExperience: 3,
  },
  {
    id: 60,
    jobFunctionId: 3,
    seniorityId: 3,
    industryId: 1,
    genderId: 2,
    userId: 60,
    salary: 68250,
    yearsOfExperience: 8,
  },
  {
    id: 61,
    jobFunctionId: 2,
    seniorityId: 4,
    industryId: 6,
    genderId: 2,
    userId: 61,
    salary: 94500,
    yearsOfExperience: 14,
  },
  {
    id: 62,
    jobFunctionId: 1,
    seniorityId: 1,
    industryId: 2,
    genderId: 1,
    userId: 62,
    salary: 42750,
    yearsOfExperience: 2,
  },
  {
    id: 63,
    jobFunctionId: 2,
    seniorityId: 2,
    industryId: 3,
    genderId: 1,
    userId: 63,
    salary: 61750,
    yearsOfExperience: 5,
  },
  {
    id: 64,
    jobFunctionId: 2,
    seniorityId: 4,
    industryId: 3,
    genderId: 1,
    userId: 64,
    salary: 114000,
    yearsOfExperience: 10,
  },
  {
    id: 65,
    jobFunctionId: 6,
    seniorityId: 5,
    industryId: 3,
    genderId: 2,
    userId: 65,
    salary: 126000,
    yearsOfExperience: 19,
  },
  {
    id: 66,
    jobFunctionId: 2,
    seniorityId: 4,
    industryId: 5,
    genderId: 2,
    userId: 66,
    salary: 94500,
    yearsOfExperience: 13,
  },
  {
    id: 67,
    jobFunctionId: 5,
    seniorityId: 5,
    industryId: 2,
    genderId: 1,
    userId: 67,
    salary: 133000,
    yearsOfExperience: 19,
  },
  {
    id: 68,
    jobFunctionId: 5,
    seniorityId: 4,
    industryId: 5,
    genderId: 2,
    userId: 68,
    salary: 94500,
    yearsOfExperience: 12,
  },
  {
    id: 69,
    jobFunctionId: 4,
    seniorityId: 2,
    industryId: 1,
    genderId: 2,
    userId: 69,
    salary: 47250,
    yearsOfExperience: 5,
  },
  {
    id: 70,
    jobFunctionId: 2,
    seniorityId: 2,
    industryId: 2,
    genderId: 1,
    userId: 70,
    salary: 61750,
    yearsOfExperience: 5,
  },
  {
    id: 71,
    jobFunctionId: 2,
    seniorityId: 4,
    industryId: 2,
    genderId: 2,
    userId: 71,
    salary: 94500,
    yearsOfExperience: 12,
  },
  {
    id: 72,
    jobFunctionId: 2,
    seniorityId: 2,
    industryId: 5,
    genderId: 1,
    userId: 72,
    salary: 61750,
    yearsOfExperience: 6,
  },
  {
    id: 73,
    jobFunctionId: 6,
    seniorityId: 3,
    industryId: 2,
    genderId: 2,
    userId: 73,
    salary: 68250,
    yearsOfExperience: 7,
  },
  {
    id: 74,
    jobFunctionId: 3,
    seniorityId: 2,
    industryId: 6,
    genderId: 1,
    userId: 74,
    salary: 61750,
    yearsOfExperience: 6,
  },
  {
    id: 75,
    jobFunctionId: 3,
    seniorityId: 1,
    industryId: 4,
    genderId: 1,
    userId: 75,
    salary: 42750,
    yearsOfExperience: 1,
  },
  {
    id: 76,
    jobFunctionId: 1,
    seniorityId: 3,
    industryId: 3,
    genderId: 2,
    userId: 76,
    salary: 68250,
    yearsOfExperience: 7,
  },
  {
    id: 77,
    jobFunctionId: 2,
    seniorityId: 2,
    industryId: 3,
    genderId: 2,
    userId: 77,
    salary: 47250,
    yearsOfExperience: 4,
  },
  {
    id: 78,
    jobFunctionId: 2,
    seniorityId: 3,
    industryId: 1,
    genderId: 1,
    userId: 78,
    salary: 85500,
    yearsOfExperience: 8,
  },
  {
    id: 79,
    jobFunctionId: 5,
    seniorityId: 2,
    industryId: 4,
    genderId: 1,
    userId: 79,
    salary: 61750,
    yearsOfExperience: 5,
  },
  {
    id: 80,
    jobFunctionId: 1,
    seniorityId: 2,
    industryId: 4,
    genderId: 1,
    userId: 80,
    salary: 61750,
    yearsOfExperience: 6,
  },
  {
    id: 81,
    jobFunctionId: 1,
    seniorityId: 3,
    industryId: 2,
    genderId: 2,
    userId: 81,
    salary: 68250,
    yearsOfExperience: 9,
  },
  {
    id: 82,
    jobFunctionId: 3,
    seniorityId: 5,
    industryId: 1,
    genderId: 2,
    userId: 82,
    salary: 126000,
    yearsOfExperience: 19,
  },
  {
    id: 83,
    jobFunctionId: 5,
    seniorityId: 5,
    industryId: 6,
    genderId: 1,
    userId: 83,
    salary: 133000,
    yearsOfExperience: 19,
  },
  {
    id: 84,
    jobFunctionId: 3,
    seniorityId: 1,
    industryId: 6,
    genderId: 1,
    userId: 84,
    salary: 42750,
    yearsOfExperience: 1,
  },
  {
    id: 85,
    jobFunctionId: 3,
    seniorityId: 3,
    industryId: 6,
    genderId: 2,
    userId: 85,
    salary: 68250,
    yearsOfExperience: 10,
  },
  {
    id: 86,
    jobFunctionId: 5,
    seniorityId: 5,
    industryId: 5,
    genderId: 1,
    userId: 86,
    salary: 133000,
    yearsOfExperience: 17,
  },
  {
    id: 87,
    jobFunctionId: 6,
    seniorityId: 5,
    industryId: 6,
    genderId: 1,
    userId: 87,
    salary: 133000,
    yearsOfExperience: 16,
  },
  {
    id: 88,
    jobFunctionId: 6,
    seniorityId: 5,
    industryId: 6,
    genderId: 1,
    userId: 88,
    salary: 133000,
    yearsOfExperience: 18,
  },
  {
    id: 89,
    jobFunctionId: 1,
    seniorityId: 5,
    industryId: 3,
    genderId: 1,
    userId: 89,
    salary: 133000,
    yearsOfExperience: 18,
  },
  {
    id: 90,
    jobFunctionId: 4,
    seniorityId: 4,
    industryId: 4,
    genderId: 2,
    userId: 90,
    salary: 94500,
    yearsOfExperience: 14,
  },
  {
    id: 91,
    jobFunctionId: 5,
    seniorityId: 1,
    industryId: 3,
    genderId: 2,
    userId: 91,
    salary: 36750,
    yearsOfExperience: 3,
  },
  {
    id: 92,
    jobFunctionId: 6,
    seniorityId: 3,
    industryId: 4,
    genderId: 1,
    userId: 92,
    salary: 85500,
    yearsOfExperience: 10,
  },
  {
    id: 93,
    jobFunctionId: 1,
    seniorityId: 2,
    industryId: 4,
    genderId: 2,
    userId: 93,
    salary: 47250,
    yearsOfExperience: 5,
  },
  {
    id: 94,
    jobFunctionId: 3,
    seniorityId: 5,
    industryId: 4,
    genderId: 2,
    userId: 94,
    salary: 126000,
    yearsOfExperience: 15,
  },
  {
    id: 95,
    jobFunctionId: 3,
    seniorityId: 3,
    industryId: 5,
    genderId: 1,
    userId: 95,
    salary: 85500,
    yearsOfExperience: 9,
  },
  {
    id: 96,
    jobFunctionId: 5,
    seniorityId: 1,
    industryId: 4,
    genderId: 1,
    userId: 96,
    salary: 42750,
    yearsOfExperience: 3,
  },
  {
    id: 97,
    jobFunctionId: 2,
    seniorityId: 1,
    industryId: 1,
    genderId: 1,
    userId: 97,
    salary: 42750,
    yearsOfExperience: 1,
  },
  {
    id: 98,
    jobFunctionId: 3,
    seniorityId: 1,
    industryId: 1,
    genderId: 1,
    userId: 98,
    salary: 42750,
    yearsOfExperience: 2,
  },
  {
    id: 99,
    jobFunctionId: 1,
    seniorityId: 4,
    industryId: 1,
    genderId: 1,
    userId: 99,
    salary: 114000,
    yearsOfExperience: 10,
  },
  {
    id: 100,
    jobFunctionId: 1,
    seniorityId: 5,
    industryId: 2,
    genderId: 2,
    userId: 100,
    salary: 126000,
    yearsOfExperience: 18,
  },
  {
    id: 101,
    jobFunctionId: 5,
    seniorityId: 4,
    industryId: 6,
    genderId: 1,
    userId: 101,
    salary: 114000,
    yearsOfExperience: 11,
  },
  {
    id: 102,
    jobFunctionId: 4,
    seniorityId: 3,
    industryId: 3,
    genderId: 2,
    userId: 102,
    salary: 68250,
    yearsOfExperience: 10,
  },
  {
    id: 103,
    jobFunctionId: 6,
    seniorityId: 5,
    industryId: 6,
    genderId: 1,
    userId: 103,
    salary: 133000,
    yearsOfExperience: 20,
  },
  {
    id: 104,
    jobFunctionId: 6,
    seniorityId: 5,
    industryId: 5,
    genderId: 1,
    userId: 104,
    salary: 133000,
    yearsOfExperience: 16,
  },
  {
    id: 105,
    jobFunctionId: 4,
    seniorityId: 3,
    industryId: 3,
    genderId: 2,
    userId: 105,
    salary: 68250,
    yearsOfExperience: 10,
  },
  {
    id: 106,
    jobFunctionId: 6,
    seniorityId: 5,
    industryId: 6,
    genderId: 2,
    userId: 106,
    salary: 126000,
    yearsOfExperience: 17,
  },
  {
    id: 107,
    jobFunctionId: 1,
    seniorityId: 5,
    industryId: 2,
    genderId: 2,
    userId: 107,
    salary: 126000,
    yearsOfExperience: 17,
  },
  {
    id: 108,
    jobFunctionId: 5,
    seniorityId: 4,
    industryId: 3,
    genderId: 2,
    userId: 108,
    salary: 94500,
    yearsOfExperience: 10,
  },
  {
    id: 109,
    jobFunctionId: 3,
    seniorityId: 5,
    industryId: 4,
    genderId: 1,
    userId: 109,
    salary: 133000,
    yearsOfExperience: 16,
  },
  {
    id: 110,
    jobFunctionId: 4,
    seniorityId: 5,
    industryId: 5,
    genderId: 1,
    userId: 110,
    salary: 133000,
    yearsOfExperience: 19,
  },
  {
    id: 111,
    jobFunctionId: 1,
    seniorityId: 2,
    industryId: 2,
    genderId: 2,
    userId: 111,
    salary: 47250,
    yearsOfExperience: 6,
  },
  {
    id: 112,
    jobFunctionId: 4,
    seniorityId: 4,
    industryId: 5,
    genderId: 2,
    userId: 112,
    salary: 94500,
    yearsOfExperience: 14,
  },
  {
    id: 113,
    jobFunctionId: 4,
    seniorityId: 2,
    industryId: 6,
    genderId: 2,
    userId: 113,
    salary: 47250,
    yearsOfExperience: 4,
  },
  {
    id: 114,
    jobFunctionId: 3,
    seniorityId: 5,
    industryId: 6,
    genderId: 2,
    userId: 114,
    salary: 126000,
    yearsOfExperience: 20,
  },
  {
    id: 115,
    jobFunctionId: 4,
    seniorityId: 3,
    industryId: 4,
    genderId: 1,
    userId: 115,
    salary: 85500,
    yearsOfExperience: 10,
  },
  {
    id: 116,
    jobFunctionId: 2,
    seniorityId: 5,
    industryId: 3,
    genderId: 1,
    userId: 116,
    salary: 133000,
    yearsOfExperience: 17,
  },
  {
    id: 117,
    jobFunctionId: 3,
    seniorityId: 4,
    industryId: 4,
    genderId: 2,
    userId: 117,
    salary: 94500,
    yearsOfExperience: 12,
  },
  {
    id: 118,
    jobFunctionId: 2,
    seniorityId: 5,
    industryId: 1,
    genderId: 2,
    userId: 118,
    salary: 126000,
    yearsOfExperience: 20,
  },
  {
    id: 119,
    jobFunctionId: 3,
    seniorityId: 4,
    industryId: 6,
    genderId: 2,
    userId: 119,
    salary: 94500,
    yearsOfExperience: 12,
  },
  {
    id: 120,
    jobFunctionId: 1,
    seniorityId: 4,
    industryId: 4,
    genderId: 2,
    userId: 120,
    salary: 94500,
    yearsOfExperience: 12,
  },
  {
    id: 121,
    jobFunctionId: 2,
    seniorityId: 5,
    industryId: 5,
    genderId: 2,
    userId: 121,
    salary: 126000,
    yearsOfExperience: 18,
  },
  {
    id: 122,
    jobFunctionId: 3,
    seniorityId: 1,
    industryId: 2,
    genderId: 2,
    userId: 122,
    salary: 36750,
    yearsOfExperience: 2,
  },
  {
    id: 123,
    jobFunctionId: 2,
    seniorityId: 3,
    industryId: 2,
    genderId: 2,
    userId: 123,
    salary: 68250,
    yearsOfExperience: 9,
  },
  {
    id: 124,
    jobFunctionId: 4,
    seniorityId: 2,
    industryId: 6,
    genderId: 2,
    userId: 124,
    salary: 47250,
    yearsOfExperience: 4,
  },
  {
    id: 125,
    jobFunctionId: 4,
    seniorityId: 2,
    industryId: 1,
    genderId: 1,
    userId: 125,
    salary: 61750,
    yearsOfExperience: 6,
  },
  {
    id: 126,
    jobFunctionId: 5,
    seniorityId: 2,
    industryId: 3,
    genderId: 2,
    userId: 126,
    salary: 47250,
    yearsOfExperience: 4,
  },
  {
    id: 127,
    jobFunctionId: 3,
    seniorityId: 4,
    industryId: 6,
    genderId: 2,
    userId: 127,
    salary: 94500,
    yearsOfExperience: 14,
  },
  {
    id: 128,
    jobFunctionId: 4,
    seniorityId: 5,
    industryId: 6,
    genderId: 2,
    userId: 128,
    salary: 126000,
    yearsOfExperience: 15,
  },
  {
    id: 129,
    jobFunctionId: 3,
    seniorityId: 1,
    industryId: 1,
    genderId: 1,
    userId: 129,
    salary: 42750,
    yearsOfExperience: 1,
  },
  {
    id: 130,
    jobFunctionId: 2,
    seniorityId: 2,
    industryId: 4,
    genderId: 1,
    userId: 130,
    salary: 61750,
    yearsOfExperience: 6,
  },
  {
    id: 131,
    jobFunctionId: 4,
    seniorityId: 1,
    industryId: 2,
    genderId: 2,
    userId: 131,
    salary: 36750,
    yearsOfExperience: 1,
  },
  {
    id: 132,
    jobFunctionId: 4,
    seniorityId: 3,
    industryId: 2,
    genderId: 2,
    userId: 132,
    salary: 68250,
    yearsOfExperience: 8,
  },
  {
    id: 133,
    jobFunctionId: 1,
    seniorityId: 3,
    industryId: 4,
    genderId: 2,
    userId: 133,
    salary: 68250,
    yearsOfExperience: 10,
  },
  {
    id: 134,
    jobFunctionId: 2,
    seniorityId: 3,
    industryId: 5,
    genderId: 2,
    userId: 134,
    salary: 68250,
    yearsOfExperience: 10,
  },
  {
    id: 135,
    jobFunctionId: 5,
    seniorityId: 5,
    industryId: 3,
    genderId: 2,
    userId: 135,
    salary: 126000,
    yearsOfExperience: 19,
  },
  {
    id: 136,
    jobFunctionId: 6,
    seniorityId: 1,
    industryId: 5,
    genderId: 2,
    userId: 136,
    salary: 36750,
    yearsOfExperience: 2,
  },
  {
    id: 137,
    jobFunctionId: 4,
    seniorityId: 4,
    industryId: 4,
    genderId: 1,
    userId: 137,
    salary: 114000,
    yearsOfExperience: 13,
  },
  {
    id: 138,
    jobFunctionId: 3,
    seniorityId: 5,
    industryId: 6,
    genderId: 2,
    userId: 138,
    salary: 126000,
    yearsOfExperience: 20,
  },
  {
    id: 139,
    jobFunctionId: 1,
    seniorityId: 2,
    industryId: 5,
    genderId: 1,
    userId: 139,
    salary: 61750,
    yearsOfExperience: 4,
  },
  {
    id: 140,
    jobFunctionId: 4,
    seniorityId: 5,
    industryId: 3,
    genderId: 1,
    userId: 140,
    salary: 133000,
    yearsOfExperience: 17,
  },
  {
    id: 141,
    jobFunctionId: 5,
    seniorityId: 2,
    industryId: 4,
    genderId: 1,
    userId: 141,
    salary: 61750,
    yearsOfExperience: 5,
  },
  {
    id: 142,
    jobFunctionId: 6,
    seniorityId: 3,
    industryId: 1,
    genderId: 1,
    userId: 142,
    salary: 85500,
    yearsOfExperience: 10,
  },
  {
    id: 143,
    jobFunctionId: 6,
    seniorityId: 5,
    industryId: 3,
    genderId: 2,
    userId: 143,
    salary: 126000,
    yearsOfExperience: 16,
  },
  {
    id: 144,
    jobFunctionId: 1,
    seniorityId: 2,
    industryId: 5,
    genderId: 1,
    userId: 144,
    salary: 61750,
    yearsOfExperience: 5,
  },
  {
    id: 145,
    jobFunctionId: 5,
    seniorityId: 4,
    industryId: 5,
    genderId: 1,
    userId: 145,
    salary: 114000,
    yearsOfExperience: 14,
  },
  {
    id: 146,
    jobFunctionId: 4,
    seniorityId: 4,
    industryId: 4,
    genderId: 1,
    userId: 146,
    salary: 114000,
    yearsOfExperience: 13,
  },
  {
    id: 147,
    jobFunctionId: 2,
    seniorityId: 3,
    industryId: 2,
    genderId: 1,
    userId: 147,
    salary: 85500,
    yearsOfExperience: 8,
  },
  {
    id: 148,
    jobFunctionId: 5,
    seniorityId: 3,
    industryId: 6,
    genderId: 1,
    userId: 148,
    salary: 85500,
    yearsOfExperience: 10,
  },
  {
    id: 149,
    jobFunctionId: 4,
    seniorityId: 2,
    industryId: 1,
    genderId: 1,
    userId: 149,
    salary: 61750,
    yearsOfExperience: 5,
  },
  {
    id: 150,
    jobFunctionId: 3,
    seniorityId: 2,
    industryId: 3,
    genderId: 1,
    userId: 150,
    salary: 61750,
    yearsOfExperience: 4,
  },
  {
    id: 151,
    jobFunctionId: 3,
    seniorityId: 1,
    industryId: 6,
    genderId: 2,
    userId: 151,
    salary: 36750,
    yearsOfExperience: 1,
  },
  {
    id: 152,
    jobFunctionId: 1,
    seniorityId: 5,
    industryId: 1,
    genderId: 1,
    userId: 152,
    salary: 133000,
    yearsOfExperience: 16,
  },
  {
    id: 153,
    jobFunctionId: 2,
    seniorityId: 2,
    industryId: 3,
    genderId: 2,
    userId: 153,
    salary: 47250,
    yearsOfExperience: 6,
  },
  {
    id: 154,
    jobFunctionId: 4,
    seniorityId: 3,
    industryId: 5,
    genderId: 1,
    userId: 154,
    salary: 85500,
    yearsOfExperience: 7,
  },
  {
    id: 155,
    jobFunctionId: 4,
    seniorityId: 1,
    industryId: 5,
    genderId: 1,
    userId: 155,
    salary: 42750,
    yearsOfExperience: 3,
  },
  {
    id: 156,
    jobFunctionId: 5,
    seniorityId: 5,
    industryId: 5,
    genderId: 2,
    userId: 156,
    salary: 126000,
    yearsOfExperience: 18,
  },
  {
    id: 157,
    jobFunctionId: 1,
    seniorityId: 5,
    industryId: 4,
    genderId: 2,
    userId: 157,
    salary: 126000,
    yearsOfExperience: 18,
  },
  {
    id: 158,
    jobFunctionId: 1,
    seniorityId: 4,
    industryId: 2,
    genderId: 2,
    userId: 158,
    salary: 94500,
    yearsOfExperience: 11,
  },
  {
    id: 159,
    jobFunctionId: 2,
    seniorityId: 1,
    industryId: 5,
    genderId: 2,
    userId: 159,
    salary: 36750,
    yearsOfExperience: 3,
  },
  {
    id: 160,
    jobFunctionId: 3,
    seniorityId: 5,
    industryId: 6,
    genderId: 2,
    userId: 160,
    salary: 126000,
    yearsOfExperience: 19,
  },
  {
    id: 161,
    jobFunctionId: 4,
    seniorityId: 2,
    industryId: 2,
    genderId: 1,
    userId: 161,
    salary: 61750,
    yearsOfExperience: 6,
  },
  {
    id: 162,
    jobFunctionId: 2,
    seniorityId: 5,
    industryId: 3,
    genderId: 2,
    userId: 162,
    salary: 126000,
    yearsOfExperience: 17,
  },
  {
    id: 163,
    jobFunctionId: 4,
    seniorityId: 2,
    industryId: 5,
    genderId: 1,
    userId: 163,
    salary: 61750,
    yearsOfExperience: 4,
  },
  {
    id: 164,
    jobFunctionId: 6,
    seniorityId: 2,
    industryId: 5,
    genderId: 2,
    userId: 164,
    salary: 47250,
    yearsOfExperience: 4,
  },
  {
    id: 165,
    jobFunctionId: 6,
    seniorityId: 4,
    industryId: 3,
    genderId: 2,
    userId: 165,
    salary: 94500,
    yearsOfExperience: 13,
  },
  {
    id: 166,
    jobFunctionId: 2,
    seniorityId: 4,
    industryId: 5,
    genderId: 2,
    userId: 166,
    salary: 94500,
    yearsOfExperience: 10,
  },
  {
    id: 167,
    jobFunctionId: 3,
    seniorityId: 5,
    industryId: 2,
    genderId: 1,
    userId: 167,
    salary: 133000,
    yearsOfExperience: 17,
  },
  {
    id: 168,
    jobFunctionId: 2,
    seniorityId: 3,
    industryId: 4,
    genderId: 1,
    userId: 168,
    salary: 85500,
    yearsOfExperience: 9,
  },
  {
    id: 169,
    jobFunctionId: 5,
    seniorityId: 3,
    industryId: 3,
    genderId: 1,
    userId: 169,
    salary: 85500,
    yearsOfExperience: 10,
  },
  {
    id: 170,
    jobFunctionId: 4,
    seniorityId: 4,
    industryId: 4,
    genderId: 2,
    userId: 170,
    salary: 94500,
    yearsOfExperience: 12,
  },
  {
    id: 171,
    jobFunctionId: 4,
    seniorityId: 1,
    industryId: 3,
    genderId: 2,
    userId: 171,
    salary: 36750,
    yearsOfExperience: 1,
  },
  {
    id: 172,
    jobFunctionId: 3,
    seniorityId: 5,
    industryId: 4,
    genderId: 1,
    userId: 172,
    salary: 133000,
    yearsOfExperience: 20,
  },
  {
    id: 173,
    jobFunctionId: 5,
    seniorityId: 2,
    industryId: 4,
    genderId: 1,
    userId: 173,
    salary: 61750,
    yearsOfExperience: 4,
  },
  {
    id: 174,
    jobFunctionId: 6,
    seniorityId: 1,
    industryId: 1,
    genderId: 1,
    userId: 174,
    salary: 42750,
    yearsOfExperience: 1,
  },
  {
    id: 175,
    jobFunctionId: 4,
    seniorityId: 3,
    industryId: 3,
    genderId: 1,
    userId: 175,
    salary: 85500,
    yearsOfExperience: 10,
  },
  {
    id: 176,
    jobFunctionId: 4,
    seniorityId: 3,
    industryId: 4,
    genderId: 1,
    userId: 176,
    salary: 85500,
    yearsOfExperience: 7,
  },
  {
    id: 177,
    jobFunctionId: 5,
    seniorityId: 4,
    industryId: 4,
    genderId: 1,
    userId: 177,
    salary: 114000,
    yearsOfExperience: 13,
  },
  {
    id: 178,
    jobFunctionId: 2,
    seniorityId: 3,
    industryId: 6,
    genderId: 2,
    userId: 178,
    salary: 68250,
    yearsOfExperience: 8,
  },
  {
    id: 179,
    jobFunctionId: 5,
    seniorityId: 3,
    industryId: 3,
    genderId: 1,
    userId: 179,
    salary: 85500,
    yearsOfExperience: 9,
  },
  {
    id: 180,
    jobFunctionId: 4,
    seniorityId: 1,
    industryId: 6,
    genderId: 1,
    userId: 180,
    salary: 42750,
    yearsOfExperience: 2,
  },
  {
    id: 181,
    jobFunctionId: 5,
    seniorityId: 4,
    industryId: 5,
    genderId: 1,
    userId: 181,
    salary: 114000,
    yearsOfExperience: 14,
  },
  {
    id: 182,
    jobFunctionId: 5,
    seniorityId: 2,
    industryId: 6,
    genderId: 1,
    userId: 182,
    salary: 61750,
    yearsOfExperience: 5,
  },
  {
    id: 183,
    jobFunctionId: 5,
    seniorityId: 1,
    industryId: 6,
    genderId: 2,
    userId: 183,
    salary: 36750,
    yearsOfExperience: 3,
  },
  {
    id: 184,
    jobFunctionId: 3,
    seniorityId: 3,
    industryId: 3,
    genderId: 1,
    userId: 184,
    salary: 85500,
    yearsOfExperience: 10,
  },
  {
    id: 185,
    jobFunctionId: 2,
    seniorityId: 1,
    industryId: 5,
    genderId: 2,
    userId: 185,
    salary: 36750,
    yearsOfExperience: 3,
  },
  {
    id: 186,
    jobFunctionId: 6,
    seniorityId: 2,
    industryId: 6,
    genderId: 2,
    userId: 186,
    salary: 47250,
    yearsOfExperience: 6,
  },
  {
    id: 187,
    jobFunctionId: 6,
    seniorityId: 5,
    industryId: 2,
    genderId: 2,
    userId: 187,
    salary: 126000,
    yearsOfExperience: 16,
  },
  {
    id: 188,
    jobFunctionId: 6,
    seniorityId: 2,
    industryId: 5,
    genderId: 2,
    userId: 188,
    salary: 47250,
    yearsOfExperience: 4,
  },
  {
    id: 189,
    jobFunctionId: 4,
    seniorityId: 3,
    industryId: 5,
    genderId: 1,
    userId: 189,
    salary: 85500,
    yearsOfExperience: 7,
  },
  {
    id: 190,
    jobFunctionId: 3,
    seniorityId: 4,
    industryId: 5,
    genderId: 1,
    userId: 190,
    salary: 114000,
    yearsOfExperience: 10,
  },
  {
    id: 191,
    jobFunctionId: 6,
    seniorityId: 5,
    industryId: 3,
    genderId: 1,
    userId: 191,
    salary: 133000,
    yearsOfExperience: 15,
  },
  {
    id: 192,
    jobFunctionId: 6,
    seniorityId: 3,
    industryId: 3,
    genderId: 1,
    userId: 192,
    salary: 85500,
    yearsOfExperience: 9,
  },
  {
    id: 193,
    jobFunctionId: 1,
    seniorityId: 4,
    industryId: 5,
    genderId: 1,
    userId: 193,
    salary: 114000,
    yearsOfExperience: 12,
  },
  {
    id: 194,
    jobFunctionId: 6,
    seniorityId: 1,
    industryId: 4,
    genderId: 2,
    userId: 194,
    salary: 36750,
    yearsOfExperience: 1,
  },
  {
    id: 195,
    jobFunctionId: 1,
    seniorityId: 2,
    industryId: 1,
    genderId: 1,
    userId: 195,
    salary: 61750,
    yearsOfExperience: 6,
  },
  {
    id: 196,
    jobFunctionId: 6,
    seniorityId: 4,
    industryId: 1,
    genderId: 2,
    userId: 196,
    salary: 94500,
    yearsOfExperience: 11,
  },
  {
    id: 197,
    jobFunctionId: 3,
    seniorityId: 1,
    industryId: 4,
    genderId: 2,
    userId: 197,
    salary: 36750,
    yearsOfExperience: 2,
  },
  {
    id: 198,
    jobFunctionId: 5,
    seniorityId: 3,
    industryId: 4,
    genderId: 2,
    userId: 198,
    salary: 68250,
    yearsOfExperience: 8,
  },
  {
    id: 199,
    jobFunctionId: 2,
    seniorityId: 1,
    industryId: 2,
    genderId: 2,
    userId: 199,
    salary: 36750,
    yearsOfExperience: 1,
  },
  {
    id: 200,
    jobFunctionId: 5,
    seniorityId: 3,
    industryId: 6,
    genderId: 1,
    userId: 200,
    salary: 85500,
    yearsOfExperience: 7,
  },
  {
    id: 201,
    jobFunctionId: 1,
    seniorityId: 4,
    industryId: 3,
    genderId: 1,
    userId: 201,
    salary: 114000,
    yearsOfExperience: 10,
  },
  {
    id: 202,
    jobFunctionId: 3,
    seniorityId: 3,
    industryId: 5,
    genderId: 1,
    userId: 202,
    salary: 85500,
    yearsOfExperience: 8,
  },
  {
    id: 203,
    jobFunctionId: 3,
    seniorityId: 1,
    industryId: 2,
    genderId: 2,
    userId: 203,
    salary: 36750,
    yearsOfExperience: 1,
  },
  {
    id: 204,
    jobFunctionId: 1,
    seniorityId: 5,
    industryId: 1,
    genderId: 1,
    userId: 204,
    salary: 133000,
    yearsOfExperience: 19,
  },
  {
    id: 205,
    jobFunctionId: 4,
    seniorityId: 1,
    industryId: 6,
    genderId: 2,
    userId: 205,
    salary: 36750,
    yearsOfExperience: 1,
  },
  {
    id: 206,
    jobFunctionId: 6,
    seniorityId: 2,
    industryId: 6,
    genderId: 2,
    userId: 206,
    salary: 47250,
    yearsOfExperience: 5,
  },
  {
    id: 207,
    jobFunctionId: 6,
    seniorityId: 5,
    industryId: 5,
    genderId: 2,
    userId: 207,
    salary: 126000,
    yearsOfExperience: 20,
  },
  {
    id: 208,
    jobFunctionId: 1,
    seniorityId: 5,
    industryId: 1,
    genderId: 2,
    userId: 208,
    salary: 126000,
    yearsOfExperience: 19,
  },
  {
    id: 209,
    jobFunctionId: 6,
    seniorityId: 1,
    industryId: 2,
    genderId: 1,
    userId: 209,
    salary: 42750,
    yearsOfExperience: 3,
  },
  {
    id: 210,
    jobFunctionId: 4,
    seniorityId: 1,
    industryId: 3,
    genderId: 1,
    userId: 210,
    salary: 42750,
    yearsOfExperience: 1,
  },
  {
    id: 211,
    jobFunctionId: 4,
    seniorityId: 5,
    industryId: 6,
    genderId: 2,
    userId: 211,
    salary: 126000,
    yearsOfExperience: 20,
  },
  {
    id: 212,
    jobFunctionId: 5,
    seniorityId: 1,
    industryId: 3,
    genderId: 2,
    userId: 212,
    salary: 36750,
    yearsOfExperience: 1,
  },
  {
    id: 213,
    jobFunctionId: 1,
    seniorityId: 4,
    industryId: 6,
    genderId: 1,
    userId: 213,
    salary: 114000,
    yearsOfExperience: 11,
  },
  {
    id: 214,
    jobFunctionId: 4,
    seniorityId: 4,
    industryId: 2,
    genderId: 1,
    userId: 214,
    salary: 114000,
    yearsOfExperience: 13,
  },
  {
    id: 215,
    jobFunctionId: 1,
    seniorityId: 1,
    industryId: 3,
    genderId: 1,
    userId: 215,
    salary: 42750,
    yearsOfExperience: 2,
  },
  {
    id: 216,
    jobFunctionId: 5,
    seniorityId: 3,
    industryId: 4,
    genderId: 1,
    userId: 216,
    salary: 85500,
    yearsOfExperience: 7,
  },
  {
    id: 217,
    jobFunctionId: 3,
    seniorityId: 4,
    industryId: 2,
    genderId: 2,
    userId: 217,
    salary: 94500,
    yearsOfExperience: 11,
  },
  {
    id: 218,
    jobFunctionId: 3,
    seniorityId: 4,
    industryId: 5,
    genderId: 2,
    userId: 218,
    salary: 94500,
    yearsOfExperience: 11,
  },
  {
    id: 219,
    jobFunctionId: 1,
    seniorityId: 5,
    industryId: 6,
    genderId: 2,
    userId: 219,
    salary: 126000,
    yearsOfExperience: 16,
  },
  {
    id: 220,
    jobFunctionId: 5,
    seniorityId: 2,
    industryId: 5,
    genderId: 1,
    userId: 220,
    salary: 61750,
    yearsOfExperience: 4,
  },
  {
    id: 221,
    jobFunctionId: 3,
    seniorityId: 3,
    industryId: 6,
    genderId: 1,
    userId: 221,
    salary: 85500,
    yearsOfExperience: 7,
  },
  {
    id: 222,
    jobFunctionId: 3,
    seniorityId: 5,
    industryId: 2,
    genderId: 2,
    userId: 222,
    salary: 126000,
    yearsOfExperience: 19,
  },
  {
    id: 223,
    jobFunctionId: 4,
    seniorityId: 4,
    industryId: 5,
    genderId: 1,
    userId: 223,
    salary: 114000,
    yearsOfExperience: 13,
  },
  {
    id: 224,
    jobFunctionId: 3,
    seniorityId: 3,
    industryId: 2,
    genderId: 1,
    userId: 224,
    salary: 85500,
    yearsOfExperience: 7,
  },
  {
    id: 225,
    jobFunctionId: 3,
    seniorityId: 3,
    industryId: 1,
    genderId: 1,
    userId: 225,
    salary: 85500,
    yearsOfExperience: 9,
  },
  {
    id: 226,
    jobFunctionId: 6,
    seniorityId: 3,
    industryId: 4,
    genderId: 1,
    userId: 226,
    salary: 85500,
    yearsOfExperience: 10,
  },
  {
    id: 227,
    jobFunctionId: 5,
    seniorityId: 3,
    industryId: 3,
    genderId: 1,
    userId: 227,
    salary: 85500,
    yearsOfExperience: 8,
  },
  {
    id: 228,
    jobFunctionId: 2,
    seniorityId: 3,
    industryId: 3,
    genderId: 1,
    userId: 228,
    salary: 85500,
    yearsOfExperience: 8,
  },
  {
    id: 229,
    jobFunctionId: 2,
    seniorityId: 1,
    industryId: 6,
    genderId: 1,
    userId: 229,
    salary: 42750,
    yearsOfExperience: 1,
  },
  {
    id: 230,
    jobFunctionId: 1,
    seniorityId: 2,
    industryId: 5,
    genderId: 1,
    userId: 230,
    salary: 61750,
    yearsOfExperience: 4,
  },
  {
    id: 231,
    jobFunctionId: 6,
    seniorityId: 2,
    industryId: 2,
    genderId: 1,
    userId: 231,
    salary: 61750,
    yearsOfExperience: 5,
  },
  {
    id: 232,
    jobFunctionId: 1,
    seniorityId: 1,
    industryId: 3,
    genderId: 1,
    userId: 232,
    salary: 42750,
    yearsOfExperience: 1,
  },
  {
    id: 233,
    jobFunctionId: 2,
    seniorityId: 2,
    industryId: 2,
    genderId: 2,
    userId: 233,
    salary: 47250,
    yearsOfExperience: 6,
  },
  {
    id: 234,
    jobFunctionId: 5,
    seniorityId: 1,
    industryId: 2,
    genderId: 2,
    userId: 234,
    salary: 36750,
    yearsOfExperience: 1,
  },
  {
    id: 235,
    jobFunctionId: 1,
    seniorityId: 5,
    industryId: 5,
    genderId: 2,
    userId: 235,
    salary: 126000,
    yearsOfExperience: 18,
  },
  {
    id: 236,
    jobFunctionId: 6,
    seniorityId: 2,
    industryId: 5,
    genderId: 1,
    userId: 236,
    salary: 61750,
    yearsOfExperience: 5,
  },
  {
    id: 237,
    jobFunctionId: 1,
    seniorityId: 1,
    industryId: 3,
    genderId: 1,
    userId: 237,
    salary: 42750,
    yearsOfExperience: 3,
  },
  {
    id: 238,
    jobFunctionId: 6,
    seniorityId: 4,
    industryId: 5,
    genderId: 1,
    userId: 238,
    salary: 114000,
    yearsOfExperience: 10,
  },
  {
    id: 239,
    jobFunctionId: 3,
    seniorityId: 2,
    industryId: 4,
    genderId: 2,
    userId: 239,
    salary: 47250,
    yearsOfExperience: 6,
  },
  {
    id: 240,
    jobFunctionId: 3,
    seniorityId: 5,
    industryId: 4,
    genderId: 1,
    userId: 240,
    salary: 133000,
    yearsOfExperience: 17,
  },
  {
    id: 241,
    jobFunctionId: 2,
    seniorityId: 2,
    industryId: 6,
    genderId: 2,
    userId: 241,
    salary: 47250,
    yearsOfExperience: 6,
  },
  {
    id: 242,
    jobFunctionId: 3,
    seniorityId: 1,
    industryId: 1,
    genderId: 2,
    userId: 242,
    salary: 36750,
    yearsOfExperience: 2,
  },
  {
    id: 243,
    jobFunctionId: 6,
    seniorityId: 3,
    industryId: 4,
    genderId: 1,
    userId: 243,
    salary: 85500,
    yearsOfExperience: 8,
  },
  {
    id: 244,
    jobFunctionId: 3,
    seniorityId: 5,
    industryId: 1,
    genderId: 1,
    userId: 244,
    salary: 126000,
    yearsOfExperience: 17,
  },
  {
    id: 245,
    jobFunctionId: 2,
    seniorityId: 1,
    industryId: 2,
    genderId: 2,
    userId: 245,
    salary: 36750,
    yearsOfExperience: 3,
  },
  {
    id: 246,
    jobFunctionId: 3,
    seniorityId: 2,
    industryId: 4,
    genderId: 1,
    userId: 246,
    salary: 61750,
    yearsOfExperience: 5,
  },
  {
    id: 247,
    jobFunctionId: 1,
    seniorityId: 4,
    industryId: 1,
    genderId: 1,
    userId: 247,
    salary: 114000,
    yearsOfExperience: 11,
  },
  {
    id: 248,
    jobFunctionId: 4,
    seniorityId: 3,
    industryId: 4,
    genderId: 1,
    userId: 248,
    salary: 85500,
    yearsOfExperience: 7,
  },
  {
    id: 249,
    jobFunctionId: 2,
    seniorityId: 2,
    industryId: 4,
    genderId: 1,
    userId: 249,
    salary: 61750,
    yearsOfExperience: 5,
  },
  {
    id: 250,
    jobFunctionId: 1,
    seniorityId: 2,
    industryId: 5,
    genderId: 1,
    userId: 250,
    salary: 61750,
    yearsOfExperience: 5,
  },
  {
    id: 251,
    jobFunctionId: 4,
    seniorityId: 3,
    industryId: 5,
    genderId: 2,
    userId: 251,
    salary: 96046,
    yearsOfExperience: 18,
  },
  {
    id: 252,
    jobFunctionId: 1,
    seniorityId: 2,
    industryId: 3,
    genderId: 1,
    userId: 252,
    salary: 52710,
    yearsOfExperience: 12,
  },
  {
    id: 253,
    jobFunctionId: 5,
    seniorityId: 4,
    industryId: 1,
    genderId: 2,
    userId: 253,
    salary: 90714,
    yearsOfExperience: 20,
  },
  {
    id: 254,
    jobFunctionId: 4,
    seniorityId: 2,
    industryId: 5,
    genderId: 2,
    userId: 254,
    salary: 66764,
    yearsOfExperience: 12,
  },
  {
    id: 255,
    jobFunctionId: 2,
    seniorityId: 2,
    industryId: 6,
    genderId: 1,
    userId: 255,
    salary: 62934,
    yearsOfExperience: 15,
  },
  {
    id: 256,
    jobFunctionId: 6,
    seniorityId: 5,
    industryId: 4,
    genderId: 1,
    userId: 256,
    salary: 123529,
    yearsOfExperience: 12,
  },
  {
    id: 257,
    jobFunctionId: 1,
    seniorityId: 1,
    industryId: 6,
    genderId: 2,
    userId: 257,
    salary: 34010,
    yearsOfExperience: 3,
  },
  {
    id: 258,
    jobFunctionId: 3,
    seniorityId: 3,
    industryId: 4,
    genderId: 2,
    userId: 258,
    salary: 81290,
    yearsOfExperience: 15,
  },
  {
    id: 259,
    jobFunctionId: 5,
    seniorityId: 3,
    industryId: 6,
    genderId: 2,
    userId: 259,
    salary: 73977,
    yearsOfExperience: 16,
  },
  {
    id: 260,
    jobFunctionId: 6,
    seniorityId: 5,
    industryId: 1,
    genderId: 2,
    userId: 260,
    salary: 114020,
    yearsOfExperience: 12,
  },
  {
    id: 261,
    jobFunctionId: 4,
    seniorityId: 4,
    industryId: 5,
    genderId: 1,
    userId: 261,
    salary: 114408,
    yearsOfExperience: 19,
  },
  {
    id: 262,
    jobFunctionId: 3,
    seniorityId: 1,
    industryId: 4,
    genderId: 1,
    userId: 262,
    salary: 36460,
    yearsOfExperience: 5,
  },
  {
    id: 263,
    jobFunctionId: 4,
    seniorityId: 4,
    industryId: 4,
    genderId: 2,
    userId: 263,
    salary: 86543,
    yearsOfExperience: 20,
  },
  {
    id: 264,
    jobFunctionId: 1,
    seniorityId: 2,
    industryId: 4,
    genderId: 1,
    userId: 264,
    salary: 62267,
    yearsOfExperience: 11,
  },
  {
    id: 265,
    jobFunctionId: 1,
    seniorityId: 3,
    industryId: 2,
    genderId: 2,
    userId: 265,
    salary: 82686,
    yearsOfExperience: 7,
  },
  {
    id: 266,
    jobFunctionId: 4,
    seniorityId: 3,
    industryId: 5,
    genderId: 2,
    userId: 266,
    salary: 90643,
    yearsOfExperience: 18,
  },
  {
    id: 267,
    jobFunctionId: 2,
    seniorityId: 5,
    industryId: 1,
    genderId: 2,
    userId: 267,
    salary: 120709,
    yearsOfExperience: 15,
  },
  {
    id: 268,
    jobFunctionId: 6,
    seniorityId: 3,
    industryId: 2,
    genderId: 2,
    userId: 268,
    salary: 97227,
    yearsOfExperience: 17,
  },
  {
    id: 269,
    jobFunctionId: 4,
    seniorityId: 2,
    industryId: 6,
    genderId: 1,
    userId: 269,
    salary: 61551,
    yearsOfExperience: 19,
  },
  {
    id: 270,
    jobFunctionId: 4,
    seniorityId: 3,
    industryId: 4,
    genderId: 1,
    userId: 270,
    salary: 75104,
    yearsOfExperience: 20,
  },
  {
    id: 271,
    jobFunctionId: 5,
    seniorityId: 3,
    industryId: 5,
    genderId: 1,
    userId: 271,
    salary: 86841,
    yearsOfExperience: 19,
  },
  {
    id: 272,
    jobFunctionId: 3,
    seniorityId: 2,
    industryId: 4,
    genderId: 1,
    userId: 272,
    salary: 55841,
    yearsOfExperience: 11,
  },
  {
    id: 273,
    jobFunctionId: 3,
    seniorityId: 1,
    industryId: 6,
    genderId: 1,
    userId: 273,
    salary: 44610,
    yearsOfExperience: 16,
  },
  {
    id: 274,
    jobFunctionId: 6,
    seniorityId: 5,
    industryId: 6,
    genderId: 1,
    userId: 274,
    salary: 114064,
    yearsOfExperience: 18,
  },
  {
    id: 275,
    jobFunctionId: 6,
    seniorityId: 4,
    industryId: 4,
    genderId: 1,
    userId: 275,
    salary: 101117,
    yearsOfExperience: 16,
  },
  {
    id: 276,
    jobFunctionId: 3,
    seniorityId: 5,
    industryId: 6,
    genderId: 2,
    userId: 276,
    salary: 126126,
    yearsOfExperience: 15,
  },
  {
    id: 277,
    jobFunctionId: 2,
    seniorityId: 2,
    industryId: 3,
    genderId: 1,
    userId: 277,
    salary: 52082,
    yearsOfExperience: 13,
  },
  {
    id: 278,
    jobFunctionId: 4,
    seniorityId: 5,
    industryId: 4,
    genderId: 1,
    userId: 278,
    salary: 128401,
    yearsOfExperience: 23,
  },
  {
    id: 279,
    jobFunctionId: 4,
    seniorityId: 2,
    industryId: 5,
    genderId: 2,
    userId: 279,
    salary: 64658,
    yearsOfExperience: 7,
  },
  {
    id: 280,
    jobFunctionId: 5,
    seniorityId: 1,
    industryId: 4,
    genderId: 1,
    userId: 280,
    salary: 33939,
    yearsOfExperience: 17,
  },
  {
    id: 281,
    jobFunctionId: 4,
    seniorityId: 2,
    industryId: 3,
    genderId: 1,
    userId: 281,
    salary: 59205,
    yearsOfExperience: 6,
  },
  {
    id: 282,
    jobFunctionId: 3,
    seniorityId: 3,
    industryId: 5,
    genderId: 2,
    userId: 282,
    salary: 88333,
    yearsOfExperience: 19,
  },
  {
    id: 283,
    jobFunctionId: 5,
    seniorityId: 4,
    industryId: 4,
    genderId: 1,
    userId: 283,
    salary: 91622,
    yearsOfExperience: 15,
  },
  {
    id: 284,
    jobFunctionId: 1,
    seniorityId: 1,
    industryId: 1,
    genderId: 1,
    userId: 284,
    salary: 39084,
    yearsOfExperience: 8,
  },
  {
    id: 285,
    jobFunctionId: 5,
    seniorityId: 1,
    industryId: 3,
    genderId: 1,
    userId: 285,
    salary: 49129,
    yearsOfExperience: 12,
  },
  {
    id: 286,
    jobFunctionId: 5,
    seniorityId: 5,
    industryId: 5,
    genderId: 2,
    userId: 286,
    salary: 135893,
    yearsOfExperience: 23,
  },
  {
    id: 287,
    jobFunctionId: 2,
    seniorityId: 4,
    industryId: 4,
    genderId: 2,
    userId: 287,
    salary: 102135,
    yearsOfExperience: 23,
  },
  {
    id: 288,
    jobFunctionId: 2,
    seniorityId: 5,
    industryId: 1,
    genderId: 2,
    userId: 288,
    salary: 124754,
    yearsOfExperience: 11,
  },
  {
    id: 289,
    jobFunctionId: 2,
    seniorityId: 1,
    industryId: 5,
    genderId: 1,
    userId: 289,
    salary: 35967,
    yearsOfExperience: 4,
  },
  {
    id: 290,
    jobFunctionId: 6,
    seniorityId: 3,
    industryId: 1,
    genderId: 2,
    userId: 290,
    salary: 70484,
    yearsOfExperience: 10,
  },
  {
    id: 291,
    jobFunctionId: 6,
    seniorityId: 2,
    industryId: 3,
    genderId: 2,
    userId: 291,
    salary: 53314,
    yearsOfExperience: 17,
  },
  {
    id: 292,
    jobFunctionId: 6,
    seniorityId: 1,
    industryId: 2,
    genderId: 2,
    userId: 292,
    salary: 49717,
    yearsOfExperience: 4,
  },
  {
    id: 293,
    jobFunctionId: 5,
    seniorityId: 3,
    industryId: 2,
    genderId: 1,
    userId: 293,
    salary: 99682,
    yearsOfExperience: 8,
  },
  {
    id: 294,
    jobFunctionId: 4,
    seniorityId: 4,
    industryId: 3,
    genderId: 1,
    userId: 294,
    salary: 109467,
    yearsOfExperience: 13,
  },
  {
    id: 295,
    jobFunctionId: 2,
    seniorityId: 4,
    industryId: 3,
    genderId: 2,
    userId: 295,
    salary: 112695,
    yearsOfExperience: 20,
  },
  {
    id: 296,
    jobFunctionId: 4,
    seniorityId: 4,
    industryId: 6,
    genderId: 2,
    userId: 296,
    salary: 101385,
    yearsOfExperience: 20,
  },
  {
    id: 297,
    jobFunctionId: 3,
    seniorityId: 1,
    industryId: 5,
    genderId: 2,
    userId: 297,
    salary: 40101,
    yearsOfExperience: 6,
  },
  {
    id: 298,
    jobFunctionId: 5,
    seniorityId: 5,
    industryId: 2,
    genderId: 2,
    userId: 298,
    salary: 139308,
    yearsOfExperience: 17,
  },
  {
    id: 299,
    jobFunctionId: 1,
    seniorityId: 2,
    industryId: 2,
    genderId: 1,
    userId: 299,
    salary: 54306,
    yearsOfExperience: 13,
  },
  {
    id: 300,
    jobFunctionId: 2,
    seniorityId: 5,
    industryId: 5,
    genderId: 1,
    userId: 300,
    salary: 142767,
    yearsOfExperience: 16,
  },
  {
    id: 301,
    jobFunctionId: 5,
    seniorityId: 2,
    industryId: 1,
    genderId: 2,
    userId: 301,
    salary: 56585,
    yearsOfExperience: 17,
  },
  {
    id: 302,
    jobFunctionId: 4,
    seniorityId: 3,
    industryId: 1,
    genderId: 2,
    userId: 302,
    salary: 75424,
    yearsOfExperience: 7,
  },
  {
    id: 303,
    jobFunctionId: 1,
    seniorityId: 5,
    industryId: 1,
    genderId: 2,
    userId: 303,
    salary: 113068,
    yearsOfExperience: 23,
  },
  {
    id: 304,
    jobFunctionId: 2,
    seniorityId: 4,
    industryId: 3,
    genderId: 2,
    userId: 304,
    salary: 107431,
    yearsOfExperience: 21,
  },
  {
    id: 305,
    jobFunctionId: 6,
    seniorityId: 3,
    industryId: 4,
    genderId: 2,
    userId: 305,
    salary: 71308,
    yearsOfExperience: 9,
  },
  {
    id: 306,
    jobFunctionId: 5,
    seniorityId: 5,
    industryId: 1,
    genderId: 1,
    userId: 306,
    salary: 124655,
    yearsOfExperience: 21,
  },
  {
    id: 307,
    jobFunctionId: 1,
    seniorityId: 3,
    industryId: 1,
    genderId: 2,
    userId: 307,
    salary: 74985,
    yearsOfExperience: 10,
  },
  {
    id: 308,
    jobFunctionId: 4,
    seniorityId: 5,
    industryId: 6,
    genderId: 2,
    userId: 308,
    salary: 114170,
    yearsOfExperience: 15,
  },
  {
    id: 309,
    jobFunctionId: 1,
    seniorityId: 3,
    industryId: 6,
    genderId: 2,
    userId: 309,
    salary: 75521,
    yearsOfExperience: 15,
  },
  {
    id: 310,
    jobFunctionId: 6,
    seniorityId: 4,
    industryId: 2,
    genderId: 2,
    userId: 310,
    salary: 113988,
    yearsOfExperience: 21,
  },
  {
    id: 311,
    jobFunctionId: 1,
    seniorityId: 2,
    industryId: 5,
    genderId: 1,
    userId: 311,
    salary: 53647,
    yearsOfExperience: 18,
  },
  {
    id: 312,
    jobFunctionId: 1,
    seniorityId: 2,
    industryId: 6,
    genderId: 2,
    userId: 312,
    salary: 48936,
    yearsOfExperience: 14,
  },
  {
    id: 313,
    jobFunctionId: 2,
    seniorityId: 2,
    industryId: 3,
    genderId: 1,
    userId: 313,
    salary: 66944,
    yearsOfExperience: 18,
  },
  {
    id: 314,
    jobFunctionId: 2,
    seniorityId: 3,
    industryId: 5,
    genderId: 1,
    userId: 314,
    salary: 92898,
    yearsOfExperience: 16,
  },
  {
    id: 315,
    jobFunctionId: 3,
    seniorityId: 5,
    industryId: 4,
    genderId: 2,
    userId: 315,
    salary: 125308,
    yearsOfExperience: 25,
  },
  {
    id: 316,
    jobFunctionId: 5,
    seniorityId: 1,
    industryId: 3,
    genderId: 2,
    userId: 316,
    salary: 36692,
    yearsOfExperience: 11,
  },
  {
    id: 317,
    jobFunctionId: 2,
    seniorityId: 1,
    industryId: 1,
    genderId: 2,
    userId: 317,
    salary: 38639,
    yearsOfExperience: 14,
  },
  {
    id: 318,
    jobFunctionId: 6,
    seniorityId: 4,
    industryId: 4,
    genderId: 2,
    userId: 318,
    salary: 99480,
    yearsOfExperience: 12,
  },
  {
    id: 319,
    jobFunctionId: 3,
    seniorityId: 2,
    industryId: 6,
    genderId: 2,
    userId: 319,
    salary: 55429,
    yearsOfExperience: 17,
  },
  {
    id: 320,
    jobFunctionId: 6,
    seniorityId: 5,
    industryId: 6,
    genderId: 1,
    userId: 320,
    salary: 125719,
    yearsOfExperience: 15,
  },
  {
    id: 321,
    jobFunctionId: 5,
    seniorityId: 1,
    industryId: 2,
    genderId: 1,
    userId: 321,
    salary: 39219,
    yearsOfExperience: 16,
  },
  {
    id: 322,
    jobFunctionId: 1,
    seniorityId: 3,
    industryId: 5,
    genderId: 2,
    userId: 322,
    salary: 96756,
    yearsOfExperience: 19,
  },
  {
    id: 323,
    jobFunctionId: 5,
    seniorityId: 1,
    industryId: 5,
    genderId: 2,
    userId: 323,
    salary: 47145,
    yearsOfExperience: 12,
  },
  {
    id: 324,
    jobFunctionId: 2,
    seniorityId: 2,
    industryId: 6,
    genderId: 2,
    userId: 324,
    salary: 58490,
    yearsOfExperience: 10,
  },
  {
    id: 325,
    jobFunctionId: 2,
    seniorityId: 4,
    industryId: 3,
    genderId: 1,
    userId: 325,
    salary: 110469,
    yearsOfExperience: 22,
  },
  {
    id: 326,
    jobFunctionId: 3,
    seniorityId: 4,
    industryId: 2,
    genderId: 1,
    userId: 326,
    salary: 103627,
    yearsOfExperience: 21,
  },
  {
    id: 327,
    jobFunctionId: 1,
    seniorityId: 1,
    industryId: 6,
    genderId: 2,
    userId: 327,
    salary: 31884,
    yearsOfExperience: 13,
  },
  {
    id: 328,
    jobFunctionId: 6,
    seniorityId: 4,
    industryId: 2,
    genderId: 2,
    userId: 328,
    salary: 121384,
    yearsOfExperience: 14,
  },
  {
    id: 329,
    jobFunctionId: 1,
    seniorityId: 1,
    industryId: 3,
    genderId: 2,
    userId: 329,
    salary: 37999,
    yearsOfExperience: 11,
  },
  {
    id: 330,
    jobFunctionId: 6,
    seniorityId: 2,
    industryId: 3,
    genderId: 2,
    userId: 330,
    salary: 52709,
    yearsOfExperience: 19,
  },
  {
    id: 331,
    jobFunctionId: 5,
    seniorityId: 3,
    industryId: 1,
    genderId: 2,
    userId: 331,
    salary: 72219,
    yearsOfExperience: 10,
  },
  {
    id: 332,
    jobFunctionId: 4,
    seniorityId: 4,
    industryId: 5,
    genderId: 2,
    userId: 332,
    salary: 113927,
    yearsOfExperience: 22,
  },
  {
    id: 333,
    jobFunctionId: 3,
    seniorityId: 5,
    industryId: 6,
    genderId: 1,
    userId: 333,
    salary: 108322,
    yearsOfExperience: 11,
  },
  {
    id: 334,
    jobFunctionId: 1,
    seniorityId: 3,
    industryId: 5,
    genderId: 2,
    userId: 334,
    salary: 93806,
    yearsOfExperience: 14,
  },
  {
    id: 335,
    jobFunctionId: 6,
    seniorityId: 4,
    industryId: 1,
    genderId: 2,
    userId: 335,
    salary: 101630,
    yearsOfExperience: 19,
  },
  {
    id: 336,
    jobFunctionId: 6,
    seniorityId: 1,
    industryId: 2,
    genderId: 1,
    userId: 336,
    salary: 49762,
    yearsOfExperience: 17,
  },
  {
    id: 337,
    jobFunctionId: 4,
    seniorityId: 4,
    industryId: 1,
    genderId: 1,
    userId: 337,
    salary: 91609,
    yearsOfExperience: 20,
  },
  {
    id: 338,
    jobFunctionId: 6,
    seniorityId: 4,
    industryId: 4,
    genderId: 1,
    userId: 338,
    salary: 89073,
    yearsOfExperience: 11,
  },
  {
    id: 339,
    jobFunctionId: 2,
    seniorityId: 1,
    industryId: 5,
    genderId: 2,
    userId: 339,
    salary: 42087,
    yearsOfExperience: 14,
  },
  {
    id: 340,
    jobFunctionId: 4,
    seniorityId: 3,
    industryId: 1,
    genderId: 2,
    userId: 340,
    salary: 65829,
    yearsOfExperience: 7,
  },
  {
    id: 341,
    jobFunctionId: 4,
    seniorityId: 1,
    industryId: 4,
    genderId: 1,
    userId: 341,
    salary: 40315,
    yearsOfExperience: 17,
  },
  {
    id: 342,
    jobFunctionId: 3,
    seniorityId: 4,
    industryId: 4,
    genderId: 2,
    userId: 342,
    salary: 89757,
    yearsOfExperience: 14,
  },
  {
    id: 343,
    jobFunctionId: 5,
    seniorityId: 4,
    industryId: 3,
    genderId: 1,
    userId: 343,
    salary: 105463,
    yearsOfExperience: 12,
  },
  {
    id: 344,
    jobFunctionId: 6,
    seniorityId: 1,
    industryId: 4,
    genderId: 2,
    userId: 344,
    salary: 40518,
    yearsOfExperience: 16,
  },
  {
    id: 345,
    jobFunctionId: 4,
    seniorityId: 4,
    industryId: 3,
    genderId: 2,
    userId: 345,
    salary: 112956,
    yearsOfExperience: 23,
  },
  {
    id: 346,
    jobFunctionId: 2,
    seniorityId: 1,
    industryId: 5,
    genderId: 1,
    userId: 346,
    salary: 37194,
    yearsOfExperience: 13,
  },
  {
    id: 347,
    jobFunctionId: 2,
    seniorityId: 2,
    industryId: 1,
    genderId: 1,
    userId: 347,
    salary: 46044,
    yearsOfExperience: 13,
  },
  {
    id: 348,
    jobFunctionId: 5,
    seniorityId: 5,
    industryId: 3,
    genderId: 2,
    userId: 348,
    salary: 141473,
    yearsOfExperience: 12,
  },
  {
    id: 349,
    jobFunctionId: 2,
    seniorityId: 1,
    industryId: 6,
    genderId: 2,
    userId: 349,
    salary: 40257,
    yearsOfExperience: 15,
  },
  {
    id: 350,
    jobFunctionId: 2,
    seniorityId: 2,
    industryId: 5,
    genderId: 1,
    userId: 350,
    salary: 51929,
    yearsOfExperience: 16,
  },
  {
    id: 351,
    jobFunctionId: 1,
    seniorityId: 3,
    industryId: 5,
    genderId: 1,
    userId: 351,
    salary: 92547,
    yearsOfExperience: 19,
  },
  {
    id: 352,
    jobFunctionId: 2,
    seniorityId: 4,
    industryId: 3,
    genderId: 2,
    userId: 352,
    salary: 103345,
    yearsOfExperience: 16,
  },
  {
    id: 353,
    jobFunctionId: 6,
    seniorityId: 5,
    industryId: 5,
    genderId: 1,
    userId: 353,
    salary: 131236,
    yearsOfExperience: 22,
  },
  {
    id: 354,
    jobFunctionId: 2,
    seniorityId: 2,
    industryId: 2,
    genderId: 2,
    userId: 354,
    salary: 59094,
    yearsOfExperience: 15,
  },
  {
    id: 355,
    jobFunctionId: 3,
    seniorityId: 4,
    industryId: 1,
    genderId: 2,
    userId: 355,
    salary: 92000,
    yearsOfExperience: 19,
  },
  {
    id: 356,
    jobFunctionId: 1,
    seniorityId: 3,
    industryId: 4,
    genderId: 2,
    userId: 356,
    salary: 82648,
    yearsOfExperience: 15,
  },
  {
    id: 357,
    jobFunctionId: 1,
    seniorityId: 5,
    industryId: 2,
    genderId: 2,
    userId: 357,
    salary: 150844,
    yearsOfExperience: 17,
  },
  {
    id: 358,
    jobFunctionId: 5,
    seniorityId: 3,
    industryId: 6,
    genderId: 1,
    userId: 358,
    salary: 69334,
    yearsOfExperience: 11,
  },
  {
    id: 359,
    jobFunctionId: 2,
    seniorityId: 5,
    industryId: 2,
    genderId: 2,
    userId: 359,
    salary: 151976,
    yearsOfExperience: 23,
  },
  {
    id: 360,
    jobFunctionId: 5,
    seniorityId: 4,
    industryId: 4,
    genderId: 2,
    userId: 360,
    salary: 98659,
    yearsOfExperience: 21,
  },
  {
    id: 361,
    jobFunctionId: 5,
    seniorityId: 3,
    industryId: 1,
    genderId: 2,
    userId: 361,
    salary: 69513,
    yearsOfExperience: 12,
  },
  {
    id: 362,
    jobFunctionId: 4,
    seniorityId: 3,
    industryId: 5,
    genderId: 2,
    userId: 362,
    salary: 95157,
    yearsOfExperience: 12,
  },
  {
    id: 363,
    jobFunctionId: 5,
    seniorityId: 2,
    industryId: 3,
    genderId: 2,
    userId: 363,
    salary: 57299,
    yearsOfExperience: 5,
  },
  {
    id: 364,
    jobFunctionId: 2,
    seniorityId: 4,
    industryId: 4,
    genderId: 1,
    userId: 364,
    salary: 100494,
    yearsOfExperience: 16,
  },
  {
    id: 365,
    jobFunctionId: 5,
    seniorityId: 5,
    industryId: 6,
    genderId: 2,
    userId: 365,
    salary: 123782,
    yearsOfExperience: 15,
  },
  {
    id: 366,
    jobFunctionId: 3,
    seniorityId: 5,
    industryId: 4,
    genderId: 2,
    userId: 366,
    salary: 110845,
    yearsOfExperience: 17,
  },
  {
    id: 367,
    jobFunctionId: 2,
    seniorityId: 1,
    industryId: 6,
    genderId: 2,
    userId: 367,
    salary: 41114,
    yearsOfExperience: 10,
  },
  {
    id: 368,
    jobFunctionId: 2,
    seniorityId: 1,
    industryId: 1,
    genderId: 2,
    userId: 368,
    salary: 31228,
    yearsOfExperience: 14,
  },
  {
    id: 369,
    jobFunctionId: 6,
    seniorityId: 2,
    industryId: 3,
    genderId: 1,
    userId: 369,
    salary: 56508,
    yearsOfExperience: 10,
  },
  {
    id: 370,
    jobFunctionId: 6,
    seniorityId: 2,
    industryId: 4,
    genderId: 2,
    userId: 370,
    salary: 60971,
    yearsOfExperience: 5,
  },
  {
    id: 371,
    jobFunctionId: 3,
    seniorityId: 1,
    industryId: 6,
    genderId: 2,
    userId: 371,
    salary: 37530,
    yearsOfExperience: 17,
  },
  {
    id: 372,
    jobFunctionId: 2,
    seniorityId: 1,
    industryId: 3,
    genderId: 1,
    userId: 372,
    salary: 33244,
    yearsOfExperience: 7,
  },
  {
    id: 373,
    jobFunctionId: 1,
    seniorityId: 5,
    industryId: 6,
    genderId: 1,
    userId: 373,
    salary: 129300,
    yearsOfExperience: 24,
  },
  {
    id: 374,
    jobFunctionId: 6,
    seniorityId: 1,
    industryId: 3,
    genderId: 1,
    userId: 374,
    salary: 49128,
    yearsOfExperience: 6,
  },
  {
    id: 375,
    jobFunctionId: 5,
    seniorityId: 3,
    industryId: 3,
    genderId: 2,
    userId: 375,
    salary: 92251,
    yearsOfExperience: 16,
  },
  {
    id: 376,
    jobFunctionId: 5,
    seniorityId: 3,
    industryId: 4,
    genderId: 1,
    userId: 376,
    salary: 82196,
    yearsOfExperience: 7,
  },
  {
    id: 377,
    jobFunctionId: 2,
    seniorityId: 5,
    industryId: 6,
    genderId: 2,
    userId: 377,
    salary: 106334,
    yearsOfExperience: 20,
  },
  {
    id: 378,
    jobFunctionId: 3,
    seniorityId: 4,
    industryId: 2,
    genderId: 2,
    userId: 378,
    salary: 109168,
    yearsOfExperience: 13,
  },
  {
    id: 379,
    jobFunctionId: 6,
    seniorityId: 5,
    industryId: 4,
    genderId: 2,
    userId: 379,
    salary: 124823,
    yearsOfExperience: 18,
  },
  {
    id: 380,
    jobFunctionId: 5,
    seniorityId: 3,
    industryId: 4,
    genderId: 1,
    userId: 380,
    salary: 65995,
    yearsOfExperience: 17,
  },
  {
    id: 381,
    jobFunctionId: 4,
    seniorityId: 3,
    industryId: 6,
    genderId: 1,
    userId: 381,
    salary: 81802,
    yearsOfExperience: 20,
  },
  {
    id: 382,
    jobFunctionId: 2,
    seniorityId: 1,
    industryId: 6,
    genderId: 2,
    userId: 382,
    salary: 39561,
    yearsOfExperience: 11,
  },
  {
    id: 383,
    jobFunctionId: 2,
    seniorityId: 2,
    industryId: 3,
    genderId: 2,
    userId: 383,
    salary: 54172,
    yearsOfExperience: 16,
  },
  {
    id: 384,
    jobFunctionId: 3,
    seniorityId: 3,
    industryId: 3,
    genderId: 1,
    userId: 384,
    salary: 88756,
    yearsOfExperience: 17,
  },
  {
    id: 385,
    jobFunctionId: 1,
    seniorityId: 1,
    industryId: 2,
    genderId: 2,
    userId: 385,
    salary: 45858,
    yearsOfExperience: 17,
  },
  {
    id: 386,
    jobFunctionId: 4,
    seniorityId: 4,
    industryId: 6,
    genderId: 1,
    userId: 386,
    salary: 89750,
    yearsOfExperience: 18,
  },
  {
    id: 387,
    jobFunctionId: 4,
    seniorityId: 3,
    industryId: 1,
    genderId: 1,
    userId: 387,
    salary: 83046,
    yearsOfExperience: 17,
  },
  {
    id: 388,
    jobFunctionId: 5,
    seniorityId: 4,
    industryId: 5,
    genderId: 2,
    userId: 388,
    salary: 101427,
    yearsOfExperience: 17,
  },
  {
    id: 389,
    jobFunctionId: 4,
    seniorityId: 4,
    industryId: 3,
    genderId: 2,
    userId: 389,
    salary: 106418,
    yearsOfExperience: 23,
  },
  {
    id: 390,
    jobFunctionId: 2,
    seniorityId: 2,
    industryId: 5,
    genderId: 2,
    userId: 390,
    salary: 67456,
    yearsOfExperience: 19,
  },
  {
    id: 391,
    jobFunctionId: 4,
    seniorityId: 3,
    industryId: 3,
    genderId: 2,
    userId: 391,
    salary: 79105,
    yearsOfExperience: 18,
  },
  {
    id: 392,
    jobFunctionId: 3,
    seniorityId: 1,
    industryId: 4,
    genderId: 1,
    userId: 392,
    salary: 40024,
    yearsOfExperience: 13,
  },
  {
    id: 393,
    jobFunctionId: 2,
    seniorityId: 3,
    industryId: 1,
    genderId: 1,
    userId: 393,
    salary: 68707,
    yearsOfExperience: 10,
  },
  {
    id: 394,
    jobFunctionId: 2,
    seniorityId: 1,
    industryId: 6,
    genderId: 2,
    userId: 394,
    salary: 36370,
    yearsOfExperience: 6,
  },
  {
    id: 395,
    jobFunctionId: 4,
    seniorityId: 2,
    industryId: 3,
    genderId: 2,
    userId: 395,
    salary: 49513,
    yearsOfExperience: 11,
  },
  {
    id: 396,
    jobFunctionId: 5,
    seniorityId: 4,
    industryId: 2,
    genderId: 2,
    userId: 396,
    salary: 106666,
    yearsOfExperience: 17,
  },
  {
    id: 397,
    jobFunctionId: 2,
    seniorityId: 2,
    industryId: 2,
    genderId: 2,
    userId: 397,
    salary: 60447,
    yearsOfExperience: 10,
  },
  {
    id: 398,
    jobFunctionId: 1,
    seniorityId: 5,
    industryId: 4,
    genderId: 1,
    userId: 398,
    salary: 124170,
    yearsOfExperience: 13,
  },
  {
    id: 399,
    jobFunctionId: 5,
    seniorityId: 5,
    industryId: 3,
    genderId: 2,
    userId: 399,
    salary: 133513,
    yearsOfExperience: 21,
  },
  {
    id: 400,
    jobFunctionId: 4,
    seniorityId: 2,
    industryId: 4,
    genderId: 2,
    userId: 400,
    salary: 54639,
    yearsOfExperience: 19,
  },
  {
    id: 401,
    jobFunctionId: 2,
    seniorityId: 1,
    industryId: 3,
    genderId: 1,
    userId: 401,
    salary: 34928,
    yearsOfExperience: 12,
  },
  {
    id: 402,
    jobFunctionId: 2,
    seniorityId: 2,
    industryId: 2,
    genderId: 2,
    userId: 402,
    salary: 75021,
    yearsOfExperience: 15,
  },
  {
    id: 403,
    jobFunctionId: 4,
    seniorityId: 3,
    industryId: 5,
    genderId: 2,
    userId: 403,
    salary: 78795,
    yearsOfExperience: 13,
  },
  {
    id: 404,
    jobFunctionId: 6,
    seniorityId: 3,
    industryId: 5,
    genderId: 2,
    userId: 404,
    salary: 91402,
    yearsOfExperience: 18,
  },
  {
    id: 405,
    jobFunctionId: 6,
    seniorityId: 1,
    industryId: 3,
    genderId: 1,
    userId: 405,
    salary: 33262,
    yearsOfExperience: 4,
  },
  {
    id: 406,
    jobFunctionId: 1,
    seniorityId: 3,
    industryId: 5,
    genderId: 1,
    userId: 406,
    salary: 97107,
    yearsOfExperience: 14,
  },
  {
    id: 407,
    jobFunctionId: 3,
    seniorityId: 2,
    industryId: 1,
    genderId: 2,
    userId: 407,
    salary: 59239,
    yearsOfExperience: 7,
  },
  {
    id: 408,
    jobFunctionId: 6,
    seniorityId: 2,
    industryId: 1,
    genderId: 2,
    userId: 408,
    salary: 51024,
    yearsOfExperience: 10,
  },
  {
    id: 409,
    jobFunctionId: 5,
    seniorityId: 3,
    industryId: 4,
    genderId: 1,
    userId: 409,
    salary: 67483,
    yearsOfExperience: 15,
  },
  {
    id: 410,
    jobFunctionId: 4,
    seniorityId: 3,
    industryId: 4,
    genderId: 2,
    userId: 410,
    salary: 84908,
    yearsOfExperience: 20,
  },
  {
    id: 411,
    jobFunctionId: 2,
    seniorityId: 1,
    industryId: 1,
    genderId: 1,
    userId: 411,
    salary: 38387,
    yearsOfExperience: 3,
  },
  {
    id: 412,
    jobFunctionId: 6,
    seniorityId: 1,
    industryId: 2,
    genderId: 2,
    userId: 412,
    salary: 46254,
    yearsOfExperience: 12,
  },
  {
    id: 413,
    jobFunctionId: 2,
    seniorityId: 2,
    industryId: 6,
    genderId: 2,
    userId: 413,
    salary: 54036,
    yearsOfExperience: 11,
  },
  {
    id: 414,
    jobFunctionId: 4,
    seniorityId: 3,
    industryId: 4,
    genderId: 2,
    userId: 414,
    salary: 73599,
    yearsOfExperience: 16,
  },
  {
    id: 415,
    jobFunctionId: 1,
    seniorityId: 4,
    industryId: 4,
    genderId: 2,
    userId: 415,
    salary: 89637,
    yearsOfExperience: 19,
  },
  {
    id: 416,
    jobFunctionId: 4,
    seniorityId: 2,
    industryId: 5,
    genderId: 1,
    userId: 416,
    salary: 54605,
    yearsOfExperience: 14,
  },
  {
    id: 417,
    jobFunctionId: 6,
    seniorityId: 4,
    industryId: 4,
    genderId: 2,
    userId: 417,
    salary: 99871,
    yearsOfExperience: 14,
  },
  {
    id: 418,
    jobFunctionId: 2,
    seniorityId: 4,
    industryId: 4,
    genderId: 2,
    userId: 418,
    salary: 97135,
    yearsOfExperience: 20,
  },
  {
    id: 419,
    jobFunctionId: 2,
    seniorityId: 5,
    industryId: 2,
    genderId: 2,
    userId: 419,
    salary: 135230,
    yearsOfExperience: 14,
  },
  {
    id: 420,
    jobFunctionId: 4,
    seniorityId: 1,
    industryId: 4,
    genderId: 2,
    userId: 420,
    salary: 44273,
    yearsOfExperience: 15,
  },
  {
    id: 421,
    jobFunctionId: 1,
    seniorityId: 4,
    industryId: 3,
    genderId: 1,
    userId: 421,
    salary: 98723,
    yearsOfExperience: 17,
  },
  {
    id: 422,
    jobFunctionId: 5,
    seniorityId: 5,
    industryId: 2,
    genderId: 2,
    userId: 422,
    salary: 152852,
    yearsOfExperience: 24,
  },
  {
    id: 423,
    jobFunctionId: 4,
    seniorityId: 2,
    industryId: 6,
    genderId: 2,
    userId: 423,
    salary: 64514,
    yearsOfExperience: 17,
  },
  {
    id: 424,
    jobFunctionId: 5,
    seniorityId: 4,
    industryId: 1,
    genderId: 2,
    userId: 424,
    salary: 101471,
    yearsOfExperience: 22,
  },
  {
    id: 425,
    jobFunctionId: 2,
    seniorityId: 5,
    industryId: 4,
    genderId: 2,
    userId: 425,
    salary: 120987,
    yearsOfExperience: 15,
  },
  {
    id: 426,
    jobFunctionId: 6,
    seniorityId: 5,
    industryId: 2,
    genderId: 2,
    userId: 426,
    salary: 130270,
    yearsOfExperience: 14,
  },
  {
    id: 427,
    jobFunctionId: 6,
    seniorityId: 5,
    industryId: 4,
    genderId: 1,
    userId: 427,
    salary: 105105,
    yearsOfExperience: 13,
  },
  {
    id: 428,
    jobFunctionId: 4,
    seniorityId: 1,
    industryId: 5,
    genderId: 1,
    userId: 428,
    salary: 45596,
    yearsOfExperience: 3,
  },
  {
    id: 429,
    jobFunctionId: 3,
    seniorityId: 5,
    industryId: 2,
    genderId: 2,
    userId: 429,
    salary: 144648,
    yearsOfExperience: 13,
  },
  {
    id: 430,
    jobFunctionId: 4,
    seniorityId: 3,
    industryId: 3,
    genderId: 1,
    userId: 430,
    salary: 80856,
    yearsOfExperience: 19,
  },
  {
    id: 431,
    jobFunctionId: 4,
    seniorityId: 2,
    industryId: 5,
    genderId: 2,
    userId: 431,
    salary: 63144,
    yearsOfExperience: 15,
  },
  {
    id: 432,
    jobFunctionId: 1,
    seniorityId: 3,
    industryId: 4,
    genderId: 1,
    userId: 432,
    salary: 77154,
    yearsOfExperience: 12,
  },
  {
    id: 433,
    jobFunctionId: 2,
    seniorityId: 5,
    industryId: 2,
    genderId: 2,
    userId: 433,
    salary: 129746,
    yearsOfExperience: 15,
  },
  {
    id: 434,
    jobFunctionId: 2,
    seniorityId: 1,
    industryId: 4,
    genderId: 1,
    userId: 434,
    salary: 38583,
    yearsOfExperience: 12,
  },
  {
    id: 435,
    jobFunctionId: 3,
    seniorityId: 3,
    industryId: 1,
    genderId: 2,
    userId: 435,
    salary: 84143,
    yearsOfExperience: 17,
  },
  {
    id: 436,
    jobFunctionId: 4,
    seniorityId: 5,
    industryId: 3,
    genderId: 2,
    userId: 436,
    salary: 109968,
    yearsOfExperience: 20,
  },
  {
    id: 437,
    jobFunctionId: 3,
    seniorityId: 2,
    industryId: 5,
    genderId: 2,
    userId: 437,
    salary: 61717,
    yearsOfExperience: 10,
  },
  {
    id: 438,
    jobFunctionId: 2,
    seniorityId: 3,
    industryId: 2,
    genderId: 2,
    userId: 438,
    salary: 96518,
    yearsOfExperience: 15,
  },
  {
    id: 439,
    jobFunctionId: 4,
    seniorityId: 5,
    industryId: 2,
    genderId: 1,
    userId: 439,
    salary: 126036,
    yearsOfExperience: 22,
  },
  {
    id: 440,
    jobFunctionId: 5,
    seniorityId: 2,
    industryId: 2,
    genderId: 2,
    userId: 440,
    salary: 76358,
    yearsOfExperience: 16,
  },
  {
    id: 441,
    jobFunctionId: 1,
    seniorityId: 3,
    industryId: 3,
    genderId: 2,
    userId: 441,
    salary: 84874,
    yearsOfExperience: 17,
  },
  {
    id: 442,
    jobFunctionId: 4,
    seniorityId: 3,
    industryId: 4,
    genderId: 1,
    userId: 442,
    salary: 83151,
    yearsOfExperience: 18,
  },
  {
    id: 443,
    jobFunctionId: 6,
    seniorityId: 1,
    industryId: 1,
    genderId: 1,
    userId: 443,
    salary: 44638,
    yearsOfExperience: 9,
  },
  {
    id: 444,
    jobFunctionId: 2,
    seniorityId: 5,
    industryId: 6,
    genderId: 2,
    userId: 444,
    salary: 100829,
    yearsOfExperience: 16,
  },
  {
    id: 445,
    jobFunctionId: 3,
    seniorityId: 5,
    industryId: 6,
    genderId: 2,
    userId: 445,
    salary: 92194,
    yearsOfExperience: 13,
  },
  {
    id: 446,
    jobFunctionId: 4,
    seniorityId: 5,
    industryId: 2,
    genderId: 1,
    userId: 446,
    salary: 130335,
    yearsOfExperience: 16,
  },
  {
    id: 447,
    jobFunctionId: 5,
    seniorityId: 5,
    industryId: 4,
    genderId: 2,
    userId: 447,
    salary: 109904,
    yearsOfExperience: 13,
  },
  {
    id: 448,
    jobFunctionId: 6,
    seniorityId: 5,
    industryId: 3,
    genderId: 1,
    userId: 448,
    salary: 126912,
    yearsOfExperience: 11,
  },
  {
    id: 449,
    jobFunctionId: 1,
    seniorityId: 5,
    industryId: 6,
    genderId: 2,
    userId: 449,
    salary: 11511,
    yearsOfExperience: 18,
  },
  {
    id: 450,
    jobFunctionId: 2,
    seniorityId: 5,
    industryId: 2,
    genderId: 1,
    userId: 450,
    salary: 125640,
    yearsOfExperience: 15,
  },
  {
    id: 451,
    jobFunctionId: 3,
    seniorityId: 5,
    industryId: 6,
    genderId: 2,
    userId: 445,
    salary: 92194,
    yearsOfExperience: 13,
  },
  {
    id: 452,
    jobFunctionId: 4,
    seniorityId: 5,
    industryId: 2,
    genderId: 1,
    userId: 446,
    salary: 130335,
    yearsOfExperience: 16,
  },
  {
    id: 453,
    jobFunctionId: 5,
    seniorityId: 5,
    industryId: 4,
    genderId: 2,
    userId: 447,
    salary: 100904,
    yearsOfExperience: 13,
  },
  {
    id: 454,
    jobFunctionId: 6,
    seniorityId: 5,
    industryId: 3,
    genderId: 1,
    userId: 448,
    salary: 126912,
    yearsOfExperience: 11,
  },
  {
    id: 455,
    jobFunctionId: 1,
    seniorityId: 5,
    industryId: 6,
    genderId: 2,
    userId: 449,
    salary: 103511,
    yearsOfExperience: 18,
  },
  {
    id: 456,
    jobFunctionId: 2,
    seniorityId: 5,
    industryId: 2,
    genderId: 1,
    userId: 450,
    salary: 125640,
    yearsOfExperience: 15,
  },
  {
    id: 457,
    jobFunctionId: 3,
    seniorityId: 5,
    industryId: 6,
    genderId: 2,
    userId: 445,
    salary: 92194,
    yearsOfExperience: 13,
  },
  {
    id: 458,
    jobFunctionId: 4,
    seniorityId: 5,
    industryId: 2,
    genderId: 1,
    userId: 446,
    salary: 130335,
    yearsOfExperience: 16,
  },
  {
    id: 459,
    jobFunctionId: 5,
    seniorityId: 5,
    industryId: 4,
    genderId: 2,
    userId: 447,
    salary: 109904,
    yearsOfExperience: 13,
  },
  {
    id: 460,
    jobFunctionId: 6,
    seniorityId: 5,
    industryId: 3,
    genderId: 1,
    userId: 448,
    salary: 126912,
    yearsOfExperience: 11,
  },
  {
    id: 461,
    jobFunctionId: 1,
    seniorityId: 5,
    industryId: 6,
    genderId: 2,
    userId: 449,
    salary: 103511,
    yearsOfExperience: 18,
  },
  {
    id: 462,
    jobFunctionId: 2,
    seniorityId: 5,
    industryId: 2,
    genderId: 1,
    userId: 450,
    salary: 125640,
    yearsOfExperience: 15,
  },
  {
    id: 463,
    jobFunctionId: 2,
    seniorityId: 5,
    industryId: 2,
    genderId: 1,
    userId: 450,
    salary: 125640,
    yearsOfExperience: 15,
  },
  {
    id: 463,
    jobFunctionId: 3,
    seniorityId: 5,
    industryId: 6,
    genderId: 2,
    userId: 445,
    salary: 92194,
    yearsOfExperience: 13,
  },
  {
    id: 464,
    jobFunctionId: 4,
    seniorityId: 5,
    industryId: 2,
    genderId: 1,
    userId: 446,
    salary: 130335,
    yearsOfExperience: 16,
  },
  {
    id: 465,
    jobFunctionId: 5,
    seniorityId: 5,
    industryId: 4,
    genderId: 2,
    userId: 447,
    salary: 100904,
    yearsOfExperience: 13,
  },
  {
    id: 466,
    jobFunctionId: 6,
    seniorityId: 5,
    industryId: 3,
    genderId: 1,
    userId: 448,
    salary: 126912,
    yearsOfExperience: 11,
  },
  {
    id: 467,
    jobFunctionId: 1,
    seniorityId: 5,
    industryId: 6,
    genderId: 2,
    userId: 449,
    salary: 95511,
    yearsOfExperience: 18,
  },
  {
    id: 468,
    jobFunctionId: 2,
    seniorityId: 5,
    industryId: 2,
    genderId: 1,
    userId: 450,
    salary: 125640,
    yearsOfExperience: 15,
  },
  {
    id: 469,
    jobFunctionId: 3,
    seniorityId: 5,
    industryId: 6,
    genderId: 2,
    userId: 445,
    salary: 92194,
    yearsOfExperience: 13,
  },
  {
    id: 470,
    jobFunctionId: 4,
    seniorityId: 5,
    industryId: 2,
    genderId: 1,
    userId: 446,
    salary: 130335,
    yearsOfExperience: 16,
  },
  {
    id: 471,
    jobFunctionId: 5,
    seniorityId: 5,
    industryId: 4,
    genderId: 2,
    userId: 447,
    salary: 94904,
    yearsOfExperience: 13,
  },
  {
    id: 472,
    jobFunctionId: 6,
    seniorityId: 5,
    industryId: 3,
    genderId: 1,
    userId: 448,
    salary: 126912,
    yearsOfExperience: 11,
  },
  {
    id: 473,
    jobFunctionId: 1,
    seniorityId: 5,
    industryId: 6,
    genderId: 2,
    userId: 449,
    salary: 90511,
    yearsOfExperience: 18,
  },
  {
    id: 474,
    jobFunctionId: 2,
    seniorityId: 5,
    industryId: 2,
    genderId: 1,
    userId: 450,
    salary: 125640,
    yearsOfExperience: 15,
  },
];
