import type { JobInformationType } from '../migrations/00010-createtablejobinformation';

export const jobInformationDummyData: JobInformationType[] = [
  {
    id: 1,
    jobFunctionId: 4,
    seniorityId: 4,
    industryId: 6,
    genderId: 1,
    userId: 1,
    salary: 96401,
    yearsOfExperience: 12,
  },
  {
    id: 2,
    jobFunctionId: 2,
    seniorityId: 5,
    industryId: 4,
    genderId: 1,
    userId: 2,
    salary: 119212,
    yearsOfExperience: 15,
  },
  {
    id: 3,
    jobFunctionId: 4,
    seniorityId: 2,
    industryId: 1,
    genderId: 1,
    userId: 3,
    salary: 65636,
    yearsOfExperience: 19,
  },
  {
    id: 4,
    jobFunctionId: 5,
    seniorityId: 5,
    industryId: 6,
    genderId: 2,
    userId: 4,
    salary: 118338,
    yearsOfExperience: 8,
  },
  {
    id: 5,
    jobFunctionId: 4,
    seniorityId: 2,
    industryId: 6,
    genderId: 1,
    userId: 5,
    salary: 46976,
    yearsOfExperience: 17,
  },
  {
    id: 6,
    jobFunctionId: 5,
    seniorityId: 4,
    industryId: 6,
    genderId: 1,
    userId: 6,
    salary: 107040,
    yearsOfExperience: 12,
  },
  {
    id: 7,
    jobFunctionId: 1,
    seniorityId: 1,
    industryId: 6,
    genderId: 2,
    userId: 7,
    salary: 116672,
    yearsOfExperience: 10,
  },
  {
    id: 8,
    jobFunctionId: 3,
    seniorityId: 4,
    industryId: 3,
    genderId: 1,
    userId: 8,
    salary: 73976,
    yearsOfExperience: 6,
  },
  {
    id: 9,
    jobFunctionId: 6,
    seniorityId: 1,
    industryId: 2,
    genderId: 1,
    userId: 9,
    salary: 55986,
    yearsOfExperience: 16,
  },
  {
    id: 10,
    jobFunctionId: 4,
    seniorityId: 4,
    industryId: 3,
    genderId: 1,
    userId: 10,
    salary: 119882,
    yearsOfExperience: 17,
  },
  {
    id: 11,
    jobFunctionId: 5,
    seniorityId: 2,
    industryId: 2,
    genderId: 1,
    userId: 11,
    salary: 95064,
    yearsOfExperience: 10,
  },
  {
    id: 12,
    jobFunctionId: 5,
    seniorityId: 2,
    industryId: 2,
    genderId: 2,
    userId: 12,
    salary: 58440,
    yearsOfExperience: 18,
  },
  {
    id: 13,
    jobFunctionId: 3,
    seniorityId: 2,
    industryId: 1,
    genderId: 2,
    userId: 13,
    salary: 48282,
    yearsOfExperience: 2,
  },
  {
    id: 14,
    jobFunctionId: 3,
    seniorityId: 4,
    industryId: 3,
    genderId: 1,
    userId: 14,
    salary: 62655,
    yearsOfExperience: 12,
  },
  {
    id: 15,
    jobFunctionId: 6,
    seniorityId: 3,
    industryId: 6,
    genderId: 2,
    userId: 15,
    salary: 103009,
    yearsOfExperience: 8,
  },
  {
    id: 16,
    jobFunctionId: 5,
    seniorityId: 4,
    industryId: 1,
    genderId: 1,
    userId: 16,
    salary: 62138,
    yearsOfExperience: 3,
  },
  {
    id: 17,
    jobFunctionId: 1,
    seniorityId: 1,
    industryId: 2,
    genderId: 1,
    userId: 17,
    salary: 87404,
    yearsOfExperience: 18,
  },
  {
    id: 18,
    jobFunctionId: 2,
    seniorityId: 3,
    industryId: 6,
    genderId: 2,
    userId: 18,
    salary: 118342,
    yearsOfExperience: 11,
  },
  {
    id: 19,
    jobFunctionId: 3,
    seniorityId: 4,
    industryId: 5,
    genderId: 2,
    userId: 19,
    salary: 118967,
    yearsOfExperience: 9,
  },
  {
    id: 20,
    jobFunctionId: 6,
    seniorityId: 2,
    industryId: 3,
    genderId: 1,
    userId: 20,
    salary: 48217,
    yearsOfExperience: 15,
  },
  {
    id: 21,
    jobFunctionId: 2,
    seniorityId: 4,
    industryId: 5,
    genderId: 1,
    userId: 21,
    salary: 92200,
    yearsOfExperience: 8,
  },
  {
    id: 22,
    jobFunctionId: 6,
    seniorityId: 5,
    industryId: 5,
    genderId: 2,
    userId: 22,
    salary: 42661,
    yearsOfExperience: 1,
  },
  {
    id: 23,
    jobFunctionId: 2,
    seniorityId: 1,
    industryId: 1,
    genderId: 2,
    userId: 23,
    salary: 86141,
    yearsOfExperience: 14,
  },
  {
    id: 24,
    jobFunctionId: 1,
    seniorityId: 2,
    industryId: 3,
    genderId: 2,
    userId: 24,
    salary: 108177,
    yearsOfExperience: 2,
  },
  {
    id: 25,
    jobFunctionId: 5,
    seniorityId: 4,
    industryId: 6,
    genderId: 2,
    userId: 25,
    salary: 58038,
    yearsOfExperience: 15,
  },
  {
    id: 26,
    jobFunctionId: 2,
    seniorityId: 3,
    industryId: 4,
    genderId: 2,
    userId: 26,
    salary: 43465,
    yearsOfExperience: 12,
  },
  {
    id: 27,
    jobFunctionId: 1,
    seniorityId: 3,
    industryId: 3,
    genderId: 2,
    userId: 27,
    salary: 61857,
    yearsOfExperience: 10,
  },
  {
    id: 28,
    jobFunctionId: 6,
    seniorityId: 2,
    industryId: 6,
    genderId: 2,
    userId: 28,
    salary: 118379,
    yearsOfExperience: 18,
  },
  {
    id: 29,
    jobFunctionId: 5,
    seniorityId: 2,
    industryId: 1,
    genderId: 1,
    userId: 29,
    salary: 116750,
    yearsOfExperience: 12,
  },
  {
    id: 30,
    jobFunctionId: 4,
    seniorityId: 3,
    industryId: 1,
    genderId: 2,
    userId: 30,
    salary: 56330,
    yearsOfExperience: 8,
  },
  {
    id: 31,
    jobFunctionId: 2,
    seniorityId: 5,
    industryId: 4,
    genderId: 1,
    userId: 31,
    salary: 42541,
    yearsOfExperience: 18,
  },
  {
    id: 32,
    jobFunctionId: 4,
    seniorityId: 3,
    industryId: 3,
    genderId: 2,
    userId: 32,
    salary: 95832,
    yearsOfExperience: 3,
  },
  {
    id: 33,
    jobFunctionId: 1,
    seniorityId: 4,
    industryId: 3,
    genderId: 2,
    userId: 33,
    salary: 119365,
    yearsOfExperience: 2,
  },
  {
    id: 34,
    jobFunctionId: 4,
    seniorityId: 3,
    industryId: 5,
    genderId: 1,
    userId: 34,
    salary: 100050,
    yearsOfExperience: 3,
  },
  {
    id: 35,
    jobFunctionId: 5,
    seniorityId: 5,
    industryId: 5,
    genderId: 1,
    userId: 35,
    salary: 53100,
    yearsOfExperience: 2,
  },
  {
    id: 36,
    jobFunctionId: 5,
    seniorityId: 4,
    industryId: 5,
    genderId: 2,
    userId: 36,
    salary: 112520,
    yearsOfExperience: 17,
  },
  {
    id: 37,
    jobFunctionId: 5,
    seniorityId: 1,
    industryId: 6,
    genderId: 2,
    userId: 37,
    salary: 96881,
    yearsOfExperience: 15,
  },
  {
    id: 38,
    jobFunctionId: 2,
    seniorityId: 5,
    industryId: 5,
    genderId: 2,
    userId: 38,
    salary: 53724,
    yearsOfExperience: 1,
  },
  {
    id: 39,
    jobFunctionId: 3,
    seniorityId: 2,
    industryId: 3,
    genderId: 2,
    userId: 39,
    salary: 112009,
    yearsOfExperience: 10,
  },
  {
    id: 40,
    jobFunctionId: 5,
    seniorityId: 3,
    industryId: 6,
    genderId: 1,
    userId: 40,
    salary: 56988,
    yearsOfExperience: 6,
  },
  {
    id: 41,
    jobFunctionId: 4,
    seniorityId: 5,
    industryId: 4,
    genderId: 2,
    userId: 41,
    salary: 49945,
    yearsOfExperience: 4,
  },
  {
    id: 42,
    jobFunctionId: 1,
    seniorityId: 1,
    industryId: 5,
    genderId: 1,
    userId: 42,
    salary: 97261,
    yearsOfExperience: 13,
  },
  {
    id: 43,
    jobFunctionId: 5,
    seniorityId: 5,
    industryId: 2,
    genderId: 2,
    userId: 43,
    salary: 78803,
    yearsOfExperience: 5,
  },
  {
    id: 44,
    jobFunctionId: 4,
    seniorityId: 1,
    industryId: 2,
    genderId: 2,
    userId: 44,
    salary: 72533,
    yearsOfExperience: 5,
  },
  {
    id: 45,
    jobFunctionId: 5,
    seniorityId: 5,
    industryId: 1,
    genderId: 1,
    userId: 45,
    salary: 72836,
    yearsOfExperience: 11,
  },
  {
    id: 46,
    jobFunctionId: 3,
    seniorityId: 3,
    industryId: 4,
    genderId: 2,
    userId: 46,
    salary: 116674,
    yearsOfExperience: 1,
  },
  {
    id: 47,
    jobFunctionId: 1,
    seniorityId: 5,
    industryId: 6,
    genderId: 2,
    userId: 47,
    salary: 87881,
    yearsOfExperience: 16,
  },
  {
    id: 48,
    jobFunctionId: 5,
    seniorityId: 1,
    industryId: 3,
    genderId: 1,
    userId: 48,
    salary: 82700,
    yearsOfExperience: 12,
  },
  {
    id: 49,
    jobFunctionId: 4,
    seniorityId: 2,
    industryId: 5,
    genderId: 2,
    userId: 49,
    salary: 56971,
    yearsOfExperience: 11,
  },
  {
    id: 50,
    jobFunctionId: 2,
    seniorityId: 5,
    industryId: 5,
    genderId: 2,
    userId: 50,
    salary: 111340,
    yearsOfExperience: 14,
  },
  {
    id: 51,
    jobFunctionId: 4,
    seniorityId: 3,
    industryId: 5,
    genderId: 1,
    userId: 51,
    salary: 95905,
    yearsOfExperience: 6,
  },
  {
    id: 52,
    jobFunctionId: 3,
    seniorityId: 2,
    industryId: 6,
    genderId: 2,
    userId: 52,
    salary: 95666,
    yearsOfExperience: 17,
  },
  {
    id: 53,
    jobFunctionId: 6,
    seniorityId: 2,
    industryId: 1,
    genderId: 2,
    userId: 53,
    salary: 116069,
    yearsOfExperience: 13,
  },
  {
    id: 54,
    jobFunctionId: 1,
    seniorityId: 4,
    industryId: 5,
    genderId: 2,
    userId: 54,
    salary: 58183,
    yearsOfExperience: 13,
  },
  {
    id: 55,
    jobFunctionId: 6,
    seniorityId: 3,
    industryId: 3,
    genderId: 1,
    userId: 55,
    salary: 48630,
    yearsOfExperience: 15,
  },
  {
    id: 56,
    jobFunctionId: 1,
    seniorityId: 1,
    industryId: 4,
    genderId: 2,
    userId: 56,
    salary: 76887,
    yearsOfExperience: 16,
  },
  {
    id: 57,
    jobFunctionId: 6,
    seniorityId: 4,
    industryId: 3,
    genderId: 2,
    userId: 57,
    salary: 96128,
    yearsOfExperience: 14,
  },
  {
    id: 58,
    jobFunctionId: 2,
    seniorityId: 3,
    industryId: 2,
    genderId: 1,
    userId: 58,
    salary: 117103,
    yearsOfExperience: 8,
  },
  {
    id: 59,
    jobFunctionId: 2,
    seniorityId: 1,
    industryId: 2,
    genderId: 2,
    userId: 59,
    salary: 54486,
    yearsOfExperience: 19,
  },
  {
    id: 60,
    jobFunctionId: 3,
    seniorityId: 3,
    industryId: 1,
    genderId: 2,
    userId: 60,
    salary: 40091,
    yearsOfExperience: 15,
  },
  {
    id: 61,
    jobFunctionId: 2,
    seniorityId: 4,
    industryId: 6,
    genderId: 2,
    userId: 61,
    salary: 55076,
    yearsOfExperience: 14,
  },
  {
    id: 62,
    jobFunctionId: 1,
    seniorityId: 1,
    industryId: 2,
    genderId: 1,
    userId: 62,
    salary: 103980,
    yearsOfExperience: 18,
  },
  {
    id: 63,
    jobFunctionId: 2,
    seniorityId: 2,
    industryId: 3,
    genderId: 1,
    userId: 63,
    salary: 61548,
    yearsOfExperience: 20,
  },
  {
    id: 64,
    jobFunctionId: 2,
    seniorityId: 4,
    industryId: 3,
    genderId: 1,
    userId: 64,
    salary: 114618,
    yearsOfExperience: 13,
  },
  {
    id: 65,
    jobFunctionId: 6,
    seniorityId: 5,
    industryId: 3,
    genderId: 2,
    userId: 65,
    salary: 104734,
    yearsOfExperience: 3,
  },
  {
    id: 66,
    jobFunctionId: 2,
    seniorityId: 4,
    industryId: 5,
    genderId: 2,
    userId: 66,
    salary: 42569,
    yearsOfExperience: 3,
  },
  {
    id: 67,
    jobFunctionId: 5,
    seniorityId: 5,
    industryId: 2,
    genderId: 1,
    userId: 67,
    salary: 72407,
    yearsOfExperience: 4,
  },
  {
    id: 68,
    jobFunctionId: 5,
    seniorityId: 4,
    industryId: 5,
    genderId: 2,
    userId: 68,
    salary: 107051,
    yearsOfExperience: 1,
  },
  {
    id: 69,
    jobFunctionId: 4,
    seniorityId: 2,
    industryId: 1,
    genderId: 2,
    userId: 69,
    salary: 117482,
    yearsOfExperience: 15,
  },
  {
    id: 70,
    jobFunctionId: 2,
    seniorityId: 2,
    industryId: 2,
    genderId: 1,
    userId: 70,
    salary: 65029,
    yearsOfExperience: 3,
  },
  {
    id: 71,
    jobFunctionId: 2,
    seniorityId: 4,
    industryId: 2,
    genderId: 2,
    userId: 71,
    salary: 102148,
    yearsOfExperience: 10,
  },
  {
    id: 72,
    jobFunctionId: 2,
    seniorityId: 2,
    industryId: 5,
    genderId: 1,
    userId: 72,
    salary: 71903,
    yearsOfExperience: 14,
  },
  {
    id: 73,
    jobFunctionId: 6,
    seniorityId: 3,
    industryId: 2,
    genderId: 2,
    userId: 73,
    salary: 63961,
    yearsOfExperience: 11,
  },
  {
    id: 74,
    jobFunctionId: 3,
    seniorityId: 2,
    industryId: 6,
    genderId: 1,
    userId: 74,
    salary: 86546,
    yearsOfExperience: 9,
  },
  {
    id: 75,
    jobFunctionId: 3,
    seniorityId: 1,
    industryId: 4,
    genderId: 1,
    userId: 75,
    salary: 41936,
    yearsOfExperience: 14,
  },
  {
    id: 76,
    jobFunctionId: 1,
    seniorityId: 3,
    industryId: 3,
    genderId: 2,
    userId: 76,
    salary: 89301,
    yearsOfExperience: 20,
  },
  {
    id: 77,
    jobFunctionId: 2,
    seniorityId: 2,
    industryId: 3,
    genderId: 2,
    userId: 77,
    salary: 51120,
    yearsOfExperience: 2,
  },
  {
    id: 78,
    jobFunctionId: 2,
    seniorityId: 3,
    industryId: 1,
    genderId: 1,
    userId: 78,
    salary: 77324,
    yearsOfExperience: 2,
  },
  {
    id: 79,
    jobFunctionId: 5,
    seniorityId: 2,
    industryId: 4,
    genderId: 1,
    userId: 79,
    salary: 56586,
    yearsOfExperience: 14,
  },
  {
    id: 80,
    jobFunctionId: 1,
    seniorityId: 2,
    industryId: 4,
    genderId: 1,
    userId: 80,
    salary: 80583,
    yearsOfExperience: 5,
  },
  {
    id: 81,
    jobFunctionId: 1,
    seniorityId: 3,
    industryId: 2,
    genderId: 2,
    userId: 81,
    salary: 64807,
    yearsOfExperience: 10,
  },
  {
    id: 82,
    jobFunctionId: 3,
    seniorityId: 5,
    industryId: 1,
    genderId: 2,
    userId: 82,
    salary: 90150,
    yearsOfExperience: 4,
  },
  {
    id: 83,
    jobFunctionId: 5,
    seniorityId: 5,
    industryId: 6,
    genderId: 1,
    userId: 83,
    salary: 118874,
    yearsOfExperience: 3,
  },
  {
    id: 84,
    jobFunctionId: 3,
    seniorityId: 1,
    industryId: 6,
    genderId: 1,
    userId: 84,
    salary: 57543,
    yearsOfExperience: 17,
  },
  {
    id: 85,
    jobFunctionId: 3,
    seniorityId: 3,
    industryId: 6,
    genderId: 2,
    userId: 85,
    salary: 74352,
    yearsOfExperience: 8,
  },
  {
    id: 86,
    jobFunctionId: 5,
    seniorityId: 5,
    industryId: 5,
    genderId: 1,
    userId: 86,
    salary: 45280,
    yearsOfExperience: 14,
  },
  {
    id: 87,
    jobFunctionId: 6,
    seniorityId: 5,
    industryId: 6,
    genderId: 1,
    userId: 87,
    salary: 61056,
    yearsOfExperience: 9,
  },
  {
    id: 88,
    jobFunctionId: 6,
    seniorityId: 5,
    industryId: 6,
    genderId: 1,
    userId: 88,
    salary: 89151,
    yearsOfExperience: 11,
  },
  {
    id: 89,
    jobFunctionId: 1,
    seniorityId: 5,
    industryId: 3,
    genderId: 1,
    userId: 89,
    salary: 77648,
    yearsOfExperience: 10,
  },
  {
    id: 90,
    jobFunctionId: 4,
    seniorityId: 4,
    industryId: 4,
    genderId: 2,
    userId: 90,
    salary: 73668,
    yearsOfExperience: 16,
  },
  {
    id: 91,
    jobFunctionId: 5,
    seniorityId: 1,
    industryId: 3,
    genderId: 2,
    userId: 91,
    salary: 106118,
    yearsOfExperience: 18,
  },
  {
    id: 92,
    jobFunctionId: 6,
    seniorityId: 3,
    industryId: 4,
    genderId: 1,
    userId: 92,
    salary: 79914,
    yearsOfExperience: 8,
  },
  {
    id: 93,
    jobFunctionId: 1,
    seniorityId: 2,
    industryId: 4,
    genderId: 2,
    userId: 93,
    salary: 58572,
    yearsOfExperience: 16,
  },
  {
    id: 94,
    jobFunctionId: 3,
    seniorityId: 5,
    industryId: 4,
    genderId: 2,
    userId: 94,
    salary: 56041,
    yearsOfExperience: 9,
  },
  {
    id: 95,
    jobFunctionId: 3,
    seniorityId: 3,
    industryId: 5,
    genderId: 1,
    userId: 95,
    salary: 67861,
    yearsOfExperience: 6,
  },
  {
    id: 96,
    jobFunctionId: 5,
    seniorityId: 1,
    industryId: 4,
    genderId: 1,
    userId: 96,
    salary: 92898,
    yearsOfExperience: 11,
  },
  {
    id: 97,
    jobFunctionId: 2,
    seniorityId: 1,
    industryId: 1,
    genderId: 1,
    userId: 97,
    salary: 87449,
    yearsOfExperience: 1,
  },
  {
    id: 98,
    jobFunctionId: 3,
    seniorityId: 1,
    industryId: 1,
    genderId: 1,
    userId: 98,
    salary: 56508,
    yearsOfExperience: 9,
  },
  {
    id: 99,
    jobFunctionId: 1,
    seniorityId: 4,
    industryId: 1,
    genderId: 1,
    userId: 99,
    salary: 52499,
    yearsOfExperience: 3,
  },
  {
    id: 100,
    jobFunctionId: 1,
    seniorityId: 5,
    industryId: 2,
    genderId: 2,
    userId: 100,
    salary: 73381,
    yearsOfExperience: 10,
  },
];
