import type { JobInformationType } from '../migrations/00010-createtablejobinformation';

export const jobInformationDummyData: JobInformationType[] = [
  {
    id: 1,
    jobFunctionId: 4,
    seniorityId: 4,
    industryId: 6,
    genderId: 1,
    userId: 1,
    salary: 96401,
    yearsOfExperience: 12,
  },
  {
    id: 2,
    jobFunctionId: 2,
    seniorityId: 5,
    industryId: 4,
    genderId: 1,
    userId: 2,
    salary: 119212,
    yearsOfExperience: 15,
  },
  {
    id: 3,
    jobFunctionId: 4,
    seniorityId: 2,
    industryId: 1,
    genderId: 1,
    userId: 3,
    salary: 65636,
    yearsOfExperience: 19,
  },
  {
    id: 4,
    jobFunctionId: 5,
    seniorityId: 5,
    industryId: 6,
    genderId: 2,
    userId: 4,
    salary: 118338,
    yearsOfExperience: 8,
  },
  {
    id: 5,
    jobFunctionId: 4,
    seniorityId: 2,
    industryId: 6,
    genderId: 1,
    userId: 5,
    salary: 46976,
    yearsOfExperience: 17,
  },
  {
    id: 6,
    jobFunctionId: 5,
    seniorityId: 4,
    industryId: 6,
    genderId: 1,
    userId: 6,
    salary: 107040,
    yearsOfExperience: 12,
  },
  {
    id: 7,
    jobFunctionId: 1,
    seniorityId: 1,
    industryId: 6,
    genderId: 2,
    userId: 7,
    salary: 116672,
    yearsOfExperience: 10,
  },
  {
    id: 8,
    jobFunctionId: 3,
    seniorityId: 4,
    industryId: 3,
    genderId: 1,
    userId: 8,
    salary: 73976,
    yearsOfExperience: 6,
  },
  {
    id: 9,
    jobFunctionId: 6,
    seniorityId: 1,
    industryId: 2,
    genderId: 1,
    userId: 9,
    salary: 55986,
    yearsOfExperience: 16,
  },
  {
    id: 10,
    jobFunctionId: 4,
    seniorityId: 4,
    industryId: 3,
    genderId: 1,
    userId: 10,
    salary: 119882,
    yearsOfExperience: 17,
  },
  {
    id: 11,
    jobFunctionId: 5,
    seniorityId: 2,
    industryId: 2,
    genderId: 1,
    userId: 11,
    salary: 95064,
    yearsOfExperience: 10,
  },
  {
    id: 12,
    jobFunctionId: 5,
    seniorityId: 2,
    industryId: 2,
    genderId: 2,
    userId: 12,
    salary: 58440,
    yearsOfExperience: 18,
  },
  {
    id: 13,
    jobFunctionId: 3,
    seniorityId: 2,
    industryId: 1,
    genderId: 2,
    userId: 13,
    salary: 48282,
    yearsOfExperience: 2,
  },
  {
    id: 14,
    jobFunctionId: 3,
    seniorityId: 4,
    industryId: 3,
    genderId: 1,
    userId: 14,
    salary: 62655,
    yearsOfExperience: 12,
  },
  {
    id: 15,
    jobFunctionId: 6,
    seniorityId: 3,
    industryId: 6,
    genderId: 2,
    userId: 15,
    salary: 103009,
    yearsOfExperience: 8,
  },
  {
    id: 16,
    jobFunctionId: 5,
    seniorityId: 4,
    industryId: 1,
    genderId: 1,
    userId: 16,
    salary: 62138,
    yearsOfExperience: 3,
  },
  {
    id: 17,
    jobFunctionId: 1,
    seniorityId: 1,
    industryId: 2,
    genderId: 1,
    userId: 17,
    salary: 87404,
    yearsOfExperience: 18,
  },
  {
    id: 18,
    jobFunctionId: 2,
    seniorityId: 3,
    industryId: 6,
    genderId: 2,
    userId: 18,
    salary: 118342,
    yearsOfExperience: 11,
  },
  {
    id: 19,
    jobFunctionId: 3,
    seniorityId: 4,
    industryId: 5,
    genderId: 2,
    userId: 19,
    salary: 118967,
    yearsOfExperience: 9,
  },
  {
    id: 20,
    jobFunctionId: 6,
    seniorityId: 2,
    industryId: 3,
    genderId: 1,
    userId: 20,
    salary: 48217,
    yearsOfExperience: 15,
  },
  {
    id: 21,
    jobFunctionId: 2,
    seniorityId: 4,
    industryId: 5,
    genderId: 1,
    userId: 21,
    salary: 92200,
    yearsOfExperience: 8,
  },
  {
    id: 22,
    jobFunctionId: 6,
    seniorityId: 5,
    industryId: 5,
    genderId: 2,
    userId: 22,
    salary: 42661,
    yearsOfExperience: 1,
  },
  {
    id: 23,
    jobFunctionId: 2,
    seniorityId: 1,
    industryId: 1,
    genderId: 2,
    userId: 23,
    salary: 86141,
    yearsOfExperience: 14,
  },
  {
    id: 24,
    jobFunctionId: 1,
    seniorityId: 2,
    industryId: 3,
    genderId: 2,
    userId: 24,
    salary: 108177,
    yearsOfExperience: 2,
  },
  {
    id: 25,
    jobFunctionId: 5,
    seniorityId: 4,
    industryId: 6,
    genderId: 2,
    userId: 25,
    salary: 58038,
    yearsOfExperience: 15,
  },
  {
    id: 26,
    jobFunctionId: 2,
    seniorityId: 3,
    industryId: 4,
    genderId: 2,
    userId: 26,
    salary: 43465,
    yearsOfExperience: 12,
  },
  {
    id: 27,
    jobFunctionId: 1,
    seniorityId: 3,
    industryId: 3,
    genderId: 2,
    userId: 27,
    salary: 61857,
    yearsOfExperience: 10,
  },
  {
    id: 28,
    jobFunctionId: 6,
    seniorityId: 2,
    industryId: 6,
    genderId: 2,
    userId: 28,
    salary: 118379,
    yearsOfExperience: 18,
  },
  {
    id: 29,
    jobFunctionId: 5,
    seniorityId: 2,
    industryId: 1,
    genderId: 1,
    userId: 29,
    salary: 116750,
    yearsOfExperience: 12,
  },
  {
    id: 30,
    jobFunctionId: 4,
    seniorityId: 3,
    industryId: 1,
    genderId: 2,
    userId: 30,
    salary: 56330,
    yearsOfExperience: 8,
  },
  {
    id: 31,
    jobFunctionId: 2,
    seniorityId: 5,
    industryId: 4,
    genderId: 1,
    userId: 31,
    salary: 42541,
    yearsOfExperience: 18,
  },
  {
    id: 32,
    jobFunctionId: 4,
    seniorityId: 3,
    industryId: 3,
    genderId: 2,
    userId: 32,
    salary: 95832,
    yearsOfExperience: 3,
  },
  {
    id: 33,
    jobFunctionId: 1,
    seniorityId: 4,
    industryId: 3,
    genderId: 2,
    userId: 33,
    salary: 119365,
    yearsOfExperience: 2,
  },
  {
    id: 34,
    jobFunctionId: 4,
    seniorityId: 3,
    industryId: 5,
    genderId: 1,
    userId: 34,
    salary: 100050,
    yearsOfExperience: 3,
  },
  {
    id: 35,
    jobFunctionId: 5,
    seniorityId: 5,
    industryId: 5,
    genderId: 1,
    userId: 35,
    salary: 53100,
    yearsOfExperience: 2,
  },
  {
    id: 36,
    jobFunctionId: 5,
    seniorityId: 4,
    industryId: 5,
    genderId: 2,
    userId: 36,
    salary: 112520,
    yearsOfExperience: 17,
  },
  {
    id: 37,
    jobFunctionId: 5,
    seniorityId: 1,
    industryId: 6,
    genderId: 2,
    userId: 37,
    salary: 96881,
    yearsOfExperience: 15,
  },
  {
    id: 38,
    jobFunctionId: 2,
    seniorityId: 5,
    industryId: 5,
    genderId: 2,
    userId: 38,
    salary: 53724,
    yearsOfExperience: 1,
  },
  {
    id: 39,
    jobFunctionId: 3,
    seniorityId: 2,
    industryId: 3,
    genderId: 2,
    userId: 39,
    salary: 112009,
    yearsOfExperience: 10,
  },
  {
    id: 40,
    jobFunctionId: 5,
    seniorityId: 3,
    industryId: 6,
    genderId: 1,
    userId: 40,
    salary: 56988,
    yearsOfExperience: 6,
  },
  {
    id: 41,
    jobFunctionId: 4,
    seniorityId: 5,
    industryId: 4,
    genderId: 2,
    userId: 41,
    salary: 49945,
    yearsOfExperience: 4,
  },
  {
    id: 42,
    jobFunctionId: 1,
    seniorityId: 1,
    industryId: 5,
    genderId: 1,
    userId: 42,
    salary: 97261,
    yearsOfExperience: 13,
  },
  {
    id: 43,
    jobFunctionId: 5,
    seniorityId: 5,
    industryId: 2,
    genderId: 2,
    userId: 43,
    salary: 78803,
    yearsOfExperience: 5,
  },
  {
    id: 44,
    jobFunctionId: 4,
    seniorityId: 1,
    industryId: 2,
    genderId: 2,
    userId: 44,
    salary: 72533,
    yearsOfExperience: 5,
  },
  {
    id: 45,
    jobFunctionId: 5,
    seniorityId: 5,
    industryId: 1,
    genderId: 1,
    userId: 45,
    salary: 72836,
    yearsOfExperience: 11,
  },
  {
    id: 46,
    jobFunctionId: 3,
    seniorityId: 3,
    industryId: 4,
    genderId: 2,
    userId: 46,
    salary: 116674,
    yearsOfExperience: 1,
  },
  {
    id: 47,
    jobFunctionId: 1,
    seniorityId: 5,
    industryId: 6,
    genderId: 2,
    userId: 47,
    salary: 87881,
    yearsOfExperience: 16,
  },
  {
    id: 48,
    jobFunctionId: 5,
    seniorityId: 1,
    industryId: 3,
    genderId: 1,
    userId: 48,
    salary: 82700,
    yearsOfExperience: 12,
  },
  {
    id: 49,
    jobFunctionId: 4,
    seniorityId: 2,
    industryId: 5,
    genderId: 2,
    userId: 49,
    salary: 56971,
    yearsOfExperience: 11,
  },
  {
    id: 50,
    jobFunctionId: 2,
    seniorityId: 5,
    industryId: 5,
    genderId: 2,
    userId: 50,
    salary: 111340,
    yearsOfExperience: 14,
  },
  {
    id: 51,
    jobFunctionId: 4,
    seniorityId: 3,
    industryId: 5,
    genderId: 1,
    userId: 51,
    salary: 95905,
    yearsOfExperience: 6,
  },
  {
    id: 52,
    jobFunctionId: 3,
    seniorityId: 2,
    industryId: 6,
    genderId: 2,
    userId: 52,
    salary: 95666,
    yearsOfExperience: 17,
  },
  {
    id: 53,
    jobFunctionId: 6,
    seniorityId: 2,
    industryId: 1,
    genderId: 2,
    userId: 53,
    salary: 116069,
    yearsOfExperience: 13,
  },
  {
    id: 54,
    jobFunctionId: 1,
    seniorityId: 4,
    industryId: 5,
    genderId: 2,
    userId: 54,
    salary: 58183,
    yearsOfExperience: 13,
  },
  {
    id: 55,
    jobFunctionId: 6,
    seniorityId: 3,
    industryId: 3,
    genderId: 1,
    userId: 55,
    salary: 48630,
    yearsOfExperience: 15,
  },
  {
    id: 56,
    jobFunctionId: 1,
    seniorityId: 1,
    industryId: 4,
    genderId: 2,
    userId: 56,
    salary: 76887,
    yearsOfExperience: 16,
  },
  {
    id: 57,
    jobFunctionId: 6,
    seniorityId: 4,
    industryId: 3,
    genderId: 2,
    userId: 57,
    salary: 96128,
    yearsOfExperience: 14,
  },
  {
    id: 58,
    jobFunctionId: 2,
    seniorityId: 3,
    industryId: 2,
    genderId: 1,
    userId: 58,
    salary: 117103,
    yearsOfExperience: 8,
  },
  {
    id: 59,
    jobFunctionId: 2,
    seniorityId: 1,
    industryId: 2,
    genderId: 2,
    userId: 59,
    salary: 54486,
    yearsOfExperience: 19,
  },
  {
    id: 60,
    jobFunctionId: 3,
    seniorityId: 3,
    industryId: 1,
    genderId: 2,
    userId: 60,
    salary: 40091,
    yearsOfExperience: 15,
  },
  {
    id: 61,
    jobFunctionId: 2,
    seniorityId: 4,
    industryId: 6,
    genderId: 2,
    userId: 61,
    salary: 55076,
    yearsOfExperience: 14,
  },
  {
    id: 62,
    jobFunctionId: 1,
    seniorityId: 1,
    industryId: 2,
    genderId: 1,
    userId: 62,
    salary: 103980,
    yearsOfExperience: 18,
  },
  {
    id: 63,
    jobFunctionId: 2,
    seniorityId: 2,
    industryId: 3,
    genderId: 1,
    userId: 63,
    salary: 61548,
    yearsOfExperience: 20,
  },
  {
    id: 64,
    jobFunctionId: 2,
    seniorityId: 4,
    industryId: 3,
    genderId: 1,
    userId: 64,
    salary: 114618,
    yearsOfExperience: 13,
  },
  {
    id: 65,
    jobFunctionId: 6,
    seniorityId: 5,
    industryId: 3,
    genderId: 2,
    userId: 65,
    salary: 104734,
    yearsOfExperience: 3,
  },
  {
    id: 66,
    jobFunctionId: 2,
    seniorityId: 4,
    industryId: 5,
    genderId: 2,
    userId: 66,
    salary: 42569,
    yearsOfExperience: 3,
  },
  {
    id: 67,
    jobFunctionId: 5,
    seniorityId: 5,
    industryId: 2,
    genderId: 1,
    userId: 67,
    salary: 72407,
    yearsOfExperience: 4,
  },
  {
    id: 68,
    jobFunctionId: 5,
    seniorityId: 4,
    industryId: 5,
    genderId: 2,
    userId: 68,
    salary: 107051,
    yearsOfExperience: 1,
  },
  {
    id: 69,
    jobFunctionId: 4,
    seniorityId: 2,
    industryId: 1,
    genderId: 2,
    userId: 69,
    salary: 117482,
    yearsOfExperience: 15,
  },
  {
    id: 70,
    jobFunctionId: 2,
    seniorityId: 2,
    industryId: 2,
    genderId: 1,
    userId: 70,
    salary: 65029,
    yearsOfExperience: 3,
  },
  {
    id: 71,
    jobFunctionId: 2,
    seniorityId: 4,
    industryId: 2,
    genderId: 2,
    userId: 71,
    salary: 102148,
    yearsOfExperience: 10,
  },
  {
    id: 72,
    jobFunctionId: 2,
    seniorityId: 2,
    industryId: 5,
    genderId: 1,
    userId: 72,
    salary: 71903,
    yearsOfExperience: 14,
  },
  {
    id: 73,
    jobFunctionId: 6,
    seniorityId: 3,
    industryId: 2,
    genderId: 2,
    userId: 73,
    salary: 63961,
    yearsOfExperience: 11,
  },
  {
    id: 74,
    jobFunctionId: 3,
    seniorityId: 2,
    industryId: 6,
    genderId: 1,
    userId: 74,
    salary: 86546,
    yearsOfExperience: 9,
  },
  {
    id: 75,
    jobFunctionId: 3,
    seniorityId: 1,
    industryId: 4,
    genderId: 1,
    userId: 75,
    salary: 41936,
    yearsOfExperience: 14,
  },
  {
    id: 76,
    jobFunctionId: 1,
    seniorityId: 3,
    industryId: 3,
    genderId: 2,
    userId: 76,
    salary: 89301,
    yearsOfExperience: 20,
  },
  {
    id: 77,
    jobFunctionId: 2,
    seniorityId: 2,
    industryId: 3,
    genderId: 2,
    userId: 77,
    salary: 51120,
    yearsOfExperience: 2,
  },
  {
    id: 78,
    jobFunctionId: 2,
    seniorityId: 3,
    industryId: 1,
    genderId: 1,
    userId: 78,
    salary: 77324,
    yearsOfExperience: 2,
  },
  {
    id: 79,
    jobFunctionId: 5,
    seniorityId: 2,
    industryId: 4,
    genderId: 1,
    userId: 79,
    salary: 56586,
    yearsOfExperience: 14,
  },
  {
    id: 80,
    jobFunctionId: 1,
    seniorityId: 2,
    industryId: 4,
    genderId: 1,
    userId: 80,
    salary: 80583,
    yearsOfExperience: 5,
  },
  {
    id: 81,
    jobFunctionId: 1,
    seniorityId: 3,
    industryId: 2,
    genderId: 2,
    userId: 81,
    salary: 64807,
    yearsOfExperience: 10,
  },
  {
    id: 82,
    jobFunctionId: 3,
    seniorityId: 5,
    industryId: 1,
    genderId: 2,
    userId: 82,
    salary: 90150,
    yearsOfExperience: 4,
  },
  {
    id: 83,
    jobFunctionId: 5,
    seniorityId: 5,
    industryId: 6,
    genderId: 1,
    userId: 83,
    salary: 118874,
    yearsOfExperience: 3,
  },
  {
    id: 84,
    jobFunctionId: 3,
    seniorityId: 1,
    industryId: 6,
    genderId: 1,
    userId: 84,
    salary: 57543,
    yearsOfExperience: 17,
  },
  {
    id: 85,
    jobFunctionId: 3,
    seniorityId: 3,
    industryId: 6,
    genderId: 2,
    userId: 85,
    salary: 74352,
    yearsOfExperience: 8,
  },
  {
    id: 86,
    jobFunctionId: 5,
    seniorityId: 5,
    industryId: 5,
    genderId: 1,
    userId: 86,
    salary: 45280,
    yearsOfExperience: 14,
  },
  {
    id: 87,
    jobFunctionId: 6,
    seniorityId: 5,
    industryId: 6,
    genderId: 1,
    userId: 87,
    salary: 61056,
    yearsOfExperience: 9,
  },
  {
    id: 88,
    jobFunctionId: 6,
    seniorityId: 5,
    industryId: 6,
    genderId: 1,
    userId: 88,
    salary: 89151,
    yearsOfExperience: 11,
  },
  {
    id: 89,
    jobFunctionId: 1,
    seniorityId: 5,
    industryId: 3,
    genderId: 1,
    userId: 89,
    salary: 77648,
    yearsOfExperience: 10,
  },
  {
    id: 90,
    jobFunctionId: 4,
    seniorityId: 4,
    industryId: 4,
    genderId: 2,
    userId: 90,
    salary: 73668,
    yearsOfExperience: 16,
  },
  {
    id: 91,
    jobFunctionId: 5,
    seniorityId: 1,
    industryId: 3,
    genderId: 2,
    userId: 91,
    salary: 106118,
    yearsOfExperience: 18,
  },
  {
    id: 92,
    jobFunctionId: 6,
    seniorityId: 3,
    industryId: 4,
    genderId: 1,
    userId: 92,
    salary: 79914,
    yearsOfExperience: 8,
  },
  {
    id: 93,
    jobFunctionId: 1,
    seniorityId: 2,
    industryId: 4,
    genderId: 2,
    userId: 93,
    salary: 58572,
    yearsOfExperience: 16,
  },
  {
    id: 94,
    jobFunctionId: 3,
    seniorityId: 5,
    industryId: 4,
    genderId: 2,
    userId: 94,
    salary: 56041,
    yearsOfExperience: 9,
  },
  {
    id: 95,
    jobFunctionId: 3,
    seniorityId: 3,
    industryId: 5,
    genderId: 1,
    userId: 95,
    salary: 67861,
    yearsOfExperience: 6,
  },
  {
    id: 96,
    jobFunctionId: 5,
    seniorityId: 1,
    industryId: 4,
    genderId: 1,
    userId: 96,
    salary: 92898,
    yearsOfExperience: 11,
  },
  {
    id: 97,
    jobFunctionId: 2,
    seniorityId: 1,
    industryId: 1,
    genderId: 1,
    userId: 97,
    salary: 87449,
    yearsOfExperience: 1,
  },
  {
    id: 98,
    jobFunctionId: 3,
    seniorityId: 1,
    industryId: 1,
    genderId: 1,
    userId: 98,
    salary: 56508,
    yearsOfExperience: 9,
  },
  {
    id: 99,
    jobFunctionId: 1,
    seniorityId: 4,
    industryId: 1,
    genderId: 1,
    userId: 99,
    salary: 52499,
    yearsOfExperience: 3,
  },
  {
    id: 100,
    jobFunctionId: 1,
    seniorityId: 5,
    industryId: 2,
    genderId: 2,
    userId: 100,
    salary: 73381,
    yearsOfExperience: 10,
  },
  {
    id: 101,
    jobFunctionId: 5,
    seniorityId: 4,
    industryId: 6,
    genderId: 1,
    userId: 101,
    salary: 89420,
    yearsOfExperience: 9,
  },
  {
    id: 102,
    jobFunctionId: 4,
    seniorityId: 3,
    industryId: 3,
    genderId: 2,
    userId: 102,
    salary: 80375,
    yearsOfExperience: 9,
  },
  {
    id: 103,
    jobFunctionId: 6,
    seniorityId: 5,
    industryId: 6,
    genderId: 1,
    userId: 103,
    salary: 120583,
    yearsOfExperience: 9,
  },
  {
    id: 104,
    jobFunctionId: 6,
    seniorityId: 5,
    industryId: 5,
    genderId: 1,
    userId: 104,
    salary: 109755,
    yearsOfExperience: 5,
  },
  {
    id: 105,
    jobFunctionId: 4,
    seniorityId: 3,
    industryId: 3,
    genderId: 2,
    userId: 105,
    salary: 89727,
    yearsOfExperience: 16,
  },
  {
    id: 106,
    jobFunctionId: 6,
    seniorityId: 5,
    industryId: 6,
    genderId: 2,
    userId: 106,
    salary: 111308,
    yearsOfExperience: 12,
  },
  {
    id: 107,
    jobFunctionId: 1,
    seniorityId: 5,
    industryId: 2,
    genderId: 2,
    userId: 107,
    salary: 113014,
    yearsOfExperience: 13,
  },
  {
    id: 108,
    jobFunctionId: 5,
    seniorityId: 4,
    industryId: 3,
    genderId: 2,
    userId: 108,
    salary: 90356,
    yearsOfExperience: 9,
  },
  {
    id: 109,
    jobFunctionId: 3,
    seniorityId: 5,
    industryId: 4,
    genderId: 1,
    userId: 109,
    salary: 137696,
    yearsOfExperience: 6,
  },
  {
    id: 110,
    jobFunctionId: 4,
    seniorityId: 5,
    industryId: 5,
    genderId: 1,
    userId: 110,
    salary: 150794,
    yearsOfExperience: 13,
  },
  {
    id: 111,
    jobFunctionId: 1,
    seniorityId: 2,
    industryId: 2,
    genderId: 2,
    userId: 111,
    salary: 42218,
    yearsOfExperience: 12,
  },
  {
    id: 112,
    jobFunctionId: 4,
    seniorityId: 4,
    industryId: 5,
    genderId: 2,
    userId: 112,
    salary: 112135,
    yearsOfExperience: 18,
  },
  {
    id: 113,
    jobFunctionId: 4,
    seniorityId: 2,
    industryId: 6,
    genderId: 2,
    userId: 113,
    salary: 63930,
    yearsOfExperience: 5,
  },
  {
    id: 114,
    jobFunctionId: 3,
    seniorityId: 5,
    industryId: 6,
    genderId: 2,
    userId: 114,
    salary: 129140,
    yearsOfExperience: 12,
  },
  {
    id: 115,
    jobFunctionId: 4,
    seniorityId: 3,
    industryId: 4,
    genderId: 1,
    userId: 115,
    salary: 89226,
    yearsOfExperience: 15,
  },
  {
    id: 116,
    jobFunctionId: 2,
    seniorityId: 5,
    industryId: 3,
    genderId: 1,
    userId: 116,
    salary: 130717,
    yearsOfExperience: 9,
  },
  {
    id: 117,
    jobFunctionId: 3,
    seniorityId: 4,
    industryId: 4,
    genderId: 2,
    userId: 117,
    salary: 92366,
    yearsOfExperience: 18,
  },
  {
    id: 118,
    jobFunctionId: 2,
    seniorityId: 5,
    industryId: 1,
    genderId: 2,
    userId: 118,
    salary: 116451,
    yearsOfExperience: 18,
  },
  {
    id: 119,
    jobFunctionId: 3,
    seniorityId: 4,
    industryId: 6,
    genderId: 2,
    userId: 119,
    salary: 94873,
    yearsOfExperience: 5,
  },
  {
    id: 120,
    jobFunctionId: 1,
    seniorityId: 4,
    industryId: 4,
    genderId: 2,
    userId: 120,
    salary: 97217,
    yearsOfExperience: 16,
  },
  {
    id: 121,
    jobFunctionId: 2,
    seniorityId: 5,
    industryId: 5,
    genderId: 2,
    userId: 121,
    salary: 121411,
    yearsOfExperience: 19,
  },
  {
    id: 122,
    jobFunctionId: 3,
    seniorityId: 1,
    industryId: 2,
    genderId: 2,
    userId: 122,
    salary: 45467,
    yearsOfExperience: 6,
  },
  {
    id: 123,
    jobFunctionId: 2,
    seniorityId: 3,
    industryId: 2,
    genderId: 2,
    userId: 123,
    salary: 80431,
    yearsOfExperience: 13,
  },
  {
    id: 124,
    jobFunctionId: 4,
    seniorityId: 2,
    industryId: 6,
    genderId: 2,
    userId: 124,
    salary: 70048,
    yearsOfExperience: 6,
  },
  {
    id: 125,
    jobFunctionId: 4,
    seniorityId: 2,
    industryId: 1,
    genderId: 1,
    userId: 125,
    salary: 68496,
    yearsOfExperience: 7,
  },
  {
    id: 126,
    jobFunctionId: 5,
    seniorityId: 2,
    industryId: 3,
    genderId: 2,
    userId: 126,
    salary: 41690,
    yearsOfExperience: 3,
  },
  {
    id: 127,
    jobFunctionId: 3,
    seniorityId: 4,
    industryId: 6,
    genderId: 2,
    userId: 127,
    salary: 107697,
    yearsOfExperience: 19,
  },
  {
    id: 128,
    jobFunctionId: 4,
    seniorityId: 5,
    industryId: 6,
    genderId: 2,
    userId: 128,
    salary: 128303,
    yearsOfExperience: 9,
  },
  {
    id: 129,
    jobFunctionId: 3,
    seniorityId: 1,
    industryId: 1,
    genderId: 1,
    userId: 129,
    salary: 44894,
    yearsOfExperience: 10,
  },
  {
    id: 130,
    jobFunctionId: 2,
    seniorityId: 2,
    industryId: 4,
    genderId: 1,
    userId: 130,
    salary: 50238,
    yearsOfExperience: 12,
  },
  {
    id: 131,
    jobFunctionId: 4,
    seniorityId: 1,
    industryId: 2,
    genderId: 2,
    userId: 131,
    salary: 41690,
    yearsOfExperience: 11,
  },
  {
    id: 132,
    jobFunctionId: 4,
    seniorityId: 3,
    industryId: 2,
    genderId: 2,
    userId: 132,
    salary: 84695,
    yearsOfExperience: 5,
  },
  {
    id: 133,
    jobFunctionId: 1,
    seniorityId: 3,
    industryId: 4,
    genderId: 2,
    userId: 133,
    salary: 62628,
    yearsOfExperience: 19,
  },
  {
    id: 134,
    jobFunctionId: 2,
    seniorityId: 3,
    industryId: 5,
    genderId: 2,
    userId: 134,
    salary: 70657,
    yearsOfExperience: 15,
  },
  {
    id: 135,
    jobFunctionId: 5,
    seniorityId: 5,
    industryId: 3,
    genderId: 2,
    userId: 135,
    salary: 96604,
    yearsOfExperience: 14,
  },
  {
    id: 136,
    jobFunctionId: 6,
    seniorityId: 1,
    industryId: 5,
    genderId: 2,
    userId: 136,
    salary: 33253,
    yearsOfExperience: 16,
  },
  {
    id: 137,
    jobFunctionId: 4,
    seniorityId: 4,
    industryId: 4,
    genderId: 1,
    userId: 137,
    salary: 112333,
    yearsOfExperience: 9,
  },
  {
    id: 138,
    jobFunctionId: 3,
    seniorityId: 5,
    industryId: 6,
    genderId: 2,
    userId: 138,
    salary: 123667,
    yearsOfExperience: 5,
  },
  {
    id: 139,
    jobFunctionId: 1,
    seniorityId: 2,
    industryId: 5,
    genderId: 1,
    userId: 139,
    salary: 51144,
    yearsOfExperience: 15,
  },
  {
    id: 140,
    jobFunctionId: 4,
    seniorityId: 5,
    industryId: 3,
    genderId: 1,
    userId: 140,
    salary: 139405,
    yearsOfExperience: 15,
  },
  {
    id: 141,
    jobFunctionId: 5,
    seniorityId: 2,
    industryId: 4,
    genderId: 1,
    userId: 141,
    salary: 58404,
    yearsOfExperience: 6,
  },
  {
    id: 142,
    jobFunctionId: 6,
    seniorityId: 3,
    industryId: 1,
    genderId: 1,
    userId: 142,
    salary: 78571,
    yearsOfExperience: 15,
  },
  {
    id: 143,
    jobFunctionId: 6,
    seniorityId: 5,
    industryId: 3,
    genderId: 2,
    userId: 143,
    salary: 113650,
    yearsOfExperience: 13,
  },
  {
    id: 144,
    jobFunctionId: 1,
    seniorityId: 2,
    industryId: 5,
    genderId: 1,
    userId: 144,
    salary: 45990,
    yearsOfExperience: 7,
  },
  {
    id: 145,
    jobFunctionId: 5,
    seniorityId: 4,
    industryId: 5,
    genderId: 1,
    userId: 145,
    salary: 89018,
    yearsOfExperience: 16,
  },
  {
    id: 146,
    jobFunctionId: 4,
    seniorityId: 4,
    industryId: 4,
    genderId: 1,
    userId: 146,
    salary: 112239,
    yearsOfExperience: 14,
  },
  {
    id: 147,
    jobFunctionId: 2,
    seniorityId: 3,
    industryId: 2,
    genderId: 1,
    userId: 147,
    salary: 83773,
    yearsOfExperience: 8,
  },
  {
    id: 148,
    jobFunctionId: 5,
    seniorityId: 3,
    industryId: 6,
    genderId: 1,
    userId: 148,
    salary: 83993,
    yearsOfExperience: 13,
  },
  {
    id: 149,
    jobFunctionId: 4,
    seniorityId: 2,
    industryId: 1,
    genderId: 1,
    userId: 149,
    salary: 65673,
    yearsOfExperience: 19,
  },
  {
    id: 150,
    jobFunctionId: 3,
    seniorityId: 2,
    industryId: 3,
    genderId: 1,
    userId: 150,
    salary: 68620,
    yearsOfExperience: 16,
  },
  {
    id: 151,
    jobFunctionId: 3,
    seniorityId: 1,
    industryId: 6,
    genderId: 2,
    userId: 151,
    salary: 37264,
    yearsOfExperience: 11,
  },
  {
    id: 152,
    jobFunctionId: 1,
    seniorityId: 5,
    industryId: 1,
    genderId: 1,
    userId: 152,
    salary: 123924,
    yearsOfExperience: 10,
  },
  {
    id: 153,
    jobFunctionId: 2,
    seniorityId: 2,
    industryId: 3,
    genderId: 2,
    userId: 153,
    salary: 41607,
    yearsOfExperience: 10,
  },
  {
    id: 154,
    jobFunctionId: 4,
    seniorityId: 3,
    industryId: 5,
    genderId: 1,
    userId: 154,
    salary: 92075,
    yearsOfExperience: 2,
  },
  {
    id: 155,
    jobFunctionId: 4,
    seniorityId: 1,
    industryId: 5,
    genderId: 1,
    userId: 155,
    salary: 48577,
    yearsOfExperience: 12,
  },
  {
    id: 156,
    jobFunctionId: 5,
    seniorityId: 5,
    industryId: 5,
    genderId: 2,
    userId: 156,
    salary: 100384,
    yearsOfExperience: 14,
  },
  {
    id: 157,
    jobFunctionId: 1,
    seniorityId: 5,
    industryId: 4,
    genderId: 2,
    userId: 157,
    salary: 111170,
    yearsOfExperience: 2,
  },
  {
    id: 158,
    jobFunctionId: 1,
    seniorityId: 4,
    industryId: 2,
    genderId: 2,
    userId: 158,
    salary: 89181,
    yearsOfExperience: 4,
  },
  {
    id: 159,
    jobFunctionId: 2,
    seniorityId: 1,
    industryId: 5,
    genderId: 2,
    userId: 159,
    salary: 38158,
    yearsOfExperience: 2,
  },
  {
    id: 160,
    jobFunctionId: 3,
    seniorityId: 5,
    industryId: 6,
    genderId: 2,
    userId: 160,
    salary: 125961,
    yearsOfExperience: 12,
  },
  {
    id: 161,
    jobFunctionId: 4,
    seniorityId: 2,
    industryId: 2,
    genderId: 1,
    userId: 161,
    salary: 71269,
    yearsOfExperience: 1,
  },
  {
    id: 162,
    jobFunctionId: 2,
    seniorityId: 5,
    industryId: 3,
    genderId: 2,
    userId: 162,
    salary: 117760,
    yearsOfExperience: 1,
  },
  {
    id: 163,
    jobFunctionId: 4,
    seniorityId: 2,
    industryId: 5,
    genderId: 1,
    userId: 163,
    salary: 72374,
    yearsOfExperience: 5,
  },
  {
    id: 164,
    jobFunctionId: 6,
    seniorityId: 2,
    industryId: 5,
    genderId: 2,
    userId: 164,
    salary: 45537,
    yearsOfExperience: 20,
  },
  {
    id: 165,
    jobFunctionId: 6,
    seniorityId: 4,
    industryId: 3,
    genderId: 2,
    userId: 165,
    salary: 81964,
    yearsOfExperience: 16,
  },
  {
    id: 166,
    jobFunctionId: 2,
    seniorityId: 4,
    industryId: 5,
    genderId: 2,
    userId: 166,
    salary: 83142,
    yearsOfExperience: 15,
  },
  {
    id: 167,
    jobFunctionId: 3,
    seniorityId: 5,
    industryId: 2,
    genderId: 1,
    userId: 167,
    salary: 139847,
    yearsOfExperience: 11,
  },
  {
    id: 168,
    jobFunctionId: 2,
    seniorityId: 3,
    industryId: 4,
    genderId: 1,
    userId: 168,
    salary: 68359,
    yearsOfExperience: 8,
  },
  {
    id: 169,
    jobFunctionId: 5,
    seniorityId: 3,
    industryId: 3,
    genderId: 1,
    userId: 169,
    salary: 73052,
    yearsOfExperience: 7,
  },
  {
    id: 170,
    jobFunctionId: 4,
    seniorityId: 4,
    industryId: 4,
    genderId: 2,
    userId: 170,
    salary: 105846,
    yearsOfExperience: 7,
  },
  {
    id: 171,
    jobFunctionId: 4,
    seniorityId: 1,
    industryId: 3,
    genderId: 2,
    userId: 171,
    salary: 46191,
    yearsOfExperience: 8,
  },
  {
    id: 172,
    jobFunctionId: 3,
    seniorityId: 5,
    industryId: 4,
    genderId: 1,
    userId: 172,
    salary: 126180,
    yearsOfExperience: 13,
  },
  {
    id: 173,
    jobFunctionId: 5,
    seniorityId: 2,
    industryId: 4,
    genderId: 1,
    userId: 173,
    salary: 62874,
    yearsOfExperience: 10,
  },
  {
    id: 174,
    jobFunctionId: 6,
    seniorityId: 1,
    industryId: 1,
    genderId: 1,
    userId: 174,
    salary: 35229,
    yearsOfExperience: 4,
  },
  {
    id: 175,
    jobFunctionId: 4,
    seniorityId: 3,
    industryId: 3,
    genderId: 1,
    userId: 175,
    salary: 94165,
    yearsOfExperience: 12,
  },
  {
    id: 176,
    jobFunctionId: 4,
    seniorityId: 3,
    industryId: 4,
    genderId: 1,
    userId: 176,
    salary: 86134,
    yearsOfExperience: 4,
  },
  {
    id: 177,
    jobFunctionId: 5,
    seniorityId: 4,
    industryId: 4,
    genderId: 1,
    userId: 177,
    salary: 97623,
    yearsOfExperience: 12,
  },
  {
    id: 178,
    jobFunctionId: 2,
    seniorityId: 3,
    industryId: 6,
    genderId: 2,
    userId: 178,
    salary: 70829,
    yearsOfExperience: 1,
  },
  {
    id: 179,
    jobFunctionId: 5,
    seniorityId: 3,
    industryId: 3,
    genderId: 1,
    userId: 179,
    salary: 67695,
    yearsOfExperience: 1,
  },
  {
    id: 180,
    jobFunctionId: 4,
    seniorityId: 1,
    industryId: 6,
    genderId: 1,
    userId: 180,
    salary: 45478,
    yearsOfExperience: 2,
  },
  {
    id: 181,
    jobFunctionId: 5,
    seniorityId: 4,
    industryId: 5,
    genderId: 1,
    userId: 181,
    salary: 92513,
    yearsOfExperience: 15,
  },
  {
    id: 182,
    jobFunctionId: 5,
    seniorityId: 2,
    industryId: 6,
    genderId: 1,
    userId: 182,
    salary: 51233,
    yearsOfExperience: 17,
  },
  {
    id: 183,
    jobFunctionId: 5,
    seniorityId: 1,
    industryId: 6,
    genderId: 2,
    userId: 183,
    salary: 41093,
    yearsOfExperience: 5,
  },
  {
    id: 184,
    jobFunctionId: 3,
    seniorityId: 3,
    industryId: 3,
    genderId: 1,
    userId: 184,
    salary: 82035,
    yearsOfExperience: 18,
  },
  {
    id: 185,
    jobFunctionId: 2,
    seniorityId: 1,
    industryId: 5,
    genderId: 2,
    userId: 185,
    salary: 38970,
    yearsOfExperience: 3,
  },
  {
    id: 186,
    jobFunctionId: 6,
    seniorityId: 2,
    industryId: 6,
    genderId: 2,
    userId: 186,
    salary: 49262,
    yearsOfExperience: 18,
  },
  {
    id: 187,
    jobFunctionId: 6,
    seniorityId: 5,
    industryId: 2,
    genderId: 2,
    userId: 187,
    salary: 109074,
    yearsOfExperience: 11,
  },
  {
    id: 188,
    jobFunctionId: 6,
    seniorityId: 2,
    industryId: 5,
    genderId: 2,
    userId: 188,
    salary: 46527,
    yearsOfExperience: 14,
  },
  {
    id: 189,
    jobFunctionId: 4,
    seniorityId: 3,
    industryId: 5,
    genderId: 1,
    userId: 189,
    salary: 100684,
    yearsOfExperience: 15,
  },
  {
    id: 190,
    jobFunctionId: 3,
    seniorityId: 4,
    industryId: 5,
    genderId: 1,
    userId: 190,
    salary: 105122,
    yearsOfExperience: 9,
  },
  {
    id: 191,
    jobFunctionId: 6,
    seniorityId: 5,
    industryId: 3,
    genderId: 1,
    userId: 191,
    salary: 118751,
    yearsOfExperience: 11,
  },
  {
    id: 192,
    jobFunctionId: 6,
    seniorityId: 3,
    industryId: 3,
    genderId: 1,
    userId: 192,
    salary: 81592,
    yearsOfExperience: 6,
  },
  {
    id: 193,
    jobFunctionId: 1,
    seniorityId: 4,
    industryId: 5,
    genderId: 1,
    userId: 193,
    salary: 97506,
    yearsOfExperience: 18,
  },
  {
    id: 194,
    jobFunctionId: 6,
    seniorityId: 1,
    industryId: 4,
    genderId: 2,
    userId: 194,
    salary: 34073,
    yearsOfExperience: 9,
  },
  {
    id: 195,
    jobFunctionId: 1,
    seniorityId: 2,
    industryId: 1,
    genderId: 1,
    userId: 195,
    salary: 59291,
    yearsOfExperience: 13,
  },
  {
    id: 196,
    jobFunctionId: 6,
    seniorityId: 4,
    industryId: 1,
    genderId: 2,
    userId: 196,
    salary: 85763,
    yearsOfExperience: 12,
  },
  {
    id: 197,
    jobFunctionId: 3,
    seniorityId: 1,
    industryId: 4,
    genderId: 2,
    userId: 197,
    salary: 39775,
    yearsOfExperience: 14,
  },
  {
    id: 198,
    jobFunctionId: 5,
    seniorityId: 3,
    industryId: 4,
    genderId: 2,
    userId: 198,
    salary: 63540,
    yearsOfExperience: 4,
  },
  {
    id: 199,
    jobFunctionId: 2,
    seniorityId: 1,
    industryId: 2,
    genderId: 2,
    userId: 199,
    salary: 32446,
    yearsOfExperience: 7,
  },
  {
    id: 200,
    jobFunctionId: 5,
    seniorityId: 3,
    industryId: 6,
    genderId: 1,
    userId: 200,
    salary: 81837,
    yearsOfExperience: 11,
  },
  {
    id: 201,
    jobFunctionId: 1,
    seniorityId: 4,
    industryId: 3,
    genderId: 1,
    userId: 201,
    salary: 94845,
    yearsOfExperience: 7,
  },
  {
    id: 202,
    jobFunctionId: 3,
    seniorityId: 3,
    industryId: 5,
    genderId: 1,
    userId: 202,
    salary: 82351,
    yearsOfExperience: 9,
  },
  {
    id: 203,
    jobFunctionId: 3,
    seniorityId: 1,
    industryId: 2,
    genderId: 2,
    userId: 203,
    salary: 43383,
    yearsOfExperience: 16,
  },
  {
    id: 204,
    jobFunctionId: 1,
    seniorityId: 5,
    industryId: 1,
    genderId: 1,
    userId: 204,
    salary: 114047,
    yearsOfExperience: 19,
  },
  {
    id: 205,
    jobFunctionId: 4,
    seniorityId: 1,
    industryId: 6,
    genderId: 2,
    userId: 205,
    salary: 38852,
    yearsOfExperience: 16,
  },
  {
    id: 206,
    jobFunctionId: 6,
    seniorityId: 2,
    industryId: 6,
    genderId: 2,
    userId: 206,
    salary: 43551,
    yearsOfExperience: 5,
  },
  {
    id: 207,
    jobFunctionId: 6,
    seniorityId: 5,
    industryId: 5,
    genderId: 2,
    userId: 207,
    salary: 100351,
    yearsOfExperience: 7,
  },
  {
    id: 208,
    jobFunctionId: 1,
    seniorityId: 5,
    industryId: 1,
    genderId: 2,
    userId: 208,
    salary: 111444,
    yearsOfExperience: 17,
  },
  {
    id: 209,
    jobFunctionId: 6,
    seniorityId: 1,
    industryId: 2,
    genderId: 1,
    userId: 209,
    salary: 40308,
    yearsOfExperience: 16,
  },
  {
    id: 210,
    jobFunctionId: 4,
    seniorityId: 1,
    industryId: 3,
    genderId: 1,
    userId: 210,
    salary: 44513,
    yearsOfExperience: 10,
  },
  {
    id: 211,
    jobFunctionId: 4,
    seniorityId: 5,
    industryId: 6,
    genderId: 2,
    userId: 211,
    salary: 127820,
    yearsOfExperience: 15,
  },
  {
    id: 212,
    jobFunctionId: 5,
    seniorityId: 1,
    industryId: 3,
    genderId: 2,
    userId: 212,
    salary: 38646,
    yearsOfExperience: 5,
  },
  {
    id: 213,
    jobFunctionId: 1,
    seniorityId: 4,
    industryId: 6,
    genderId: 1,
    userId: 213,
    salary: 100930,
    yearsOfExperience: 17,
  },
  {
    id: 214,
    jobFunctionId: 4,
    seniorityId: 4,
    industryId: 2,
    genderId: 1,
    userId: 214,
    salary: 113461,
    yearsOfExperience: 12,
  },
  {
    id: 215,
    jobFunctionId: 1,
    seniorityId: 1,
    industryId: 3,
    genderId: 1,
    userId: 215,
    salary: 39757,
    yearsOfExperience: 4,
  },
  {
    id: 216,
    jobFunctionId: 5,
    seniorityId: 3,
    industryId: 4,
    genderId: 1,
    userId: 216,
    salary: 75765,
    yearsOfExperience: 14,
  },
  {
    id: 217,
    jobFunctionId: 3,
    seniorityId: 4,
    industryId: 2,
    genderId: 2,
    userId: 217,
    salary: 93975,
    yearsOfExperience: 12,
  },
  {
    id: 218,
    jobFunctionId: 3,
    seniorityId: 4,
    industryId: 5,
    genderId: 2,
    userId: 218,
    salary: 111992,
    yearsOfExperience: 12,
  },
  {
    id: 219,
    jobFunctionId: 1,
    seniorityId: 5,
    industryId: 6,
    genderId: 2,
    userId: 219,
    salary: 107624,
    yearsOfExperience: 9,
  },
  {
    id: 220,
    jobFunctionId: 5,
    seniorityId: 2,
    industryId: 5,
    genderId: 1,
    userId: 220,
    salary: 62676,
    yearsOfExperience: 16,
  },
  {
    id: 221,
    jobFunctionId: 3,
    seniorityId: 3,
    industryId: 6,
    genderId: 1,
    userId: 221,
    salary: 82310,
    yearsOfExperience: 17,
  },
  {
    id: 222,
    jobFunctionId: 3,
    seniorityId: 5,
    industryId: 2,
    genderId: 2,
    userId: 222,
    salary: 123957,
    yearsOfExperience: 7,
  },
  {
    id: 223,
    jobFunctionId: 4,
    seniorityId: 4,
    industryId: 5,
    genderId: 1,
    userId: 223,
    salary: 121996,
    yearsOfExperience: 3,
  },
  {
    id: 224,
    jobFunctionId: 3,
    seniorityId: 3,
    industryId: 2,
    genderId: 1,
    userId: 224,
    salary: 92584,
    yearsOfExperience: 17,
  },
  {
    id: 225,
    jobFunctionId: 3,
    seniorityId: 3,
    industryId: 1,
    genderId: 1,
    userId: 225,
    salary: 84436,
    yearsOfExperience: 4,
  },
  {
    id: 226,
    jobFunctionId: 6,
    seniorityId: 3,
    industryId: 4,
    genderId: 1,
    userId: 226,
    salary: 82714,
    yearsOfExperience: 11,
  },
  {
    id: 227,
    jobFunctionId: 5,
    seniorityId: 3,
    industryId: 3,
    genderId: 1,
    userId: 227,
    salary: 74629,
    yearsOfExperience: 3,
  },
  {
    id: 228,
    jobFunctionId: 2,
    seniorityId: 3,
    industryId: 3,
    genderId: 1,
    userId: 228,
    salary: 88788,
    yearsOfExperience: 18,
  },
  {
    id: 229,
    jobFunctionId: 2,
    seniorityId: 1,
    industryId: 6,
    genderId: 1,
    userId: 229,
    salary: 39689,
    yearsOfExperience: 1,
  },
  {
    id: 230,
    jobFunctionId: 1,
    seniorityId: 2,
    industryId: 5,
    genderId: 1,
    userId: 230,
    salary: 49622,
    yearsOfExperience: 1,
  },
  {
    id: 231,
    jobFunctionId: 6,
    seniorityId: 2,
    industryId: 2,
    genderId: 1,
    userId: 231,
    salary: 62276,
    yearsOfExperience: 2,
  },
  {
    id: 232,
    jobFunctionId: 1,
    seniorityId: 1,
    industryId: 3,
    genderId: 1,
    userId: 232,
    salary: 39614,
    yearsOfExperience: 4,
  },
  {
    id: 233,
    jobFunctionId: 2,
    seniorityId: 2,
    industryId: 2,
    genderId: 2,
    userId: 233,
    salary: 45200,
    yearsOfExperience: 4,
  },
  {
    id: 234,
    jobFunctionId: 5,
    seniorityId: 1,
    industryId: 2,
    genderId: 2,
    userId: 234,
    salary: 37024,
    yearsOfExperience: 5,
  },
  {
    id: 235,
    jobFunctionId: 1,
    seniorityId: 5,
    industryId: 5,
    genderId: 2,
    userId: 235,
    salary: 110956,
    yearsOfExperience: 16,
  },
  {
    id: 236,
    jobFunctionId: 6,
    seniorityId: 2,
    industryId: 5,
    genderId: 1,
    userId: 236,
    salary: 59569,
    yearsOfExperience: 9,
  },
  {
    id: 237,
    jobFunctionId: 1,
    seniorityId: 1,
    industryId: 3,
    genderId: 1,
    userId: 237,
    salary: 41087,
    yearsOfExperience: 11,
  },
  {
    id: 238,
    jobFunctionId: 6,
    seniorityId: 4,
    industryId: 5,
    genderId: 1,
    userId: 238,
    salary: 90106,
    yearsOfExperience: 6,
  },
  {
    id: 239,
    jobFunctionId: 3,
    seniorityId: 2,
    industryId: 4,
    genderId: 2,
    userId: 239,
    salary: 51192,
    yearsOfExperience: 20,
  },
  {
    id: 240,
    jobFunctionId: 3,
    seniorityId: 5,
    industryId: 4,
    genderId: 1,
    userId: 240,
    salary: 134736,
    yearsOfExperience: 12,
  },
  {
    id: 241,
    jobFunctionId: 2,
    seniorityId: 2,
    industryId: 6,
    genderId: 2,
    userId: 241,
    salary: 55522,
    yearsOfExperience: 17,
  },
  {
    id: 242,
    jobFunctionId: 3,
    seniorityId: 1,
    industryId: 1,
    genderId: 2,
    userId: 242,
    salary: 42941,
    yearsOfExperience: 1,
  },
  {
    id: 243,
    jobFunctionId: 6,
    seniorityId: 3,
    industryId: 4,
    genderId: 1,
    userId: 243,
    salary: 66220,
    yearsOfExperience: 13,
  },
  {
    id: 244,
    jobFunctionId: 3,
    seniorityId: 5,
    industryId: 1,
    genderId: 2,
    userId: 244,
    salary: 122671,
    yearsOfExperience: 14,
  },
  {
    id: 245,
    jobFunctionId: 2,
    seniorityId: 1,
    industryId: 2,
    genderId: 2,
    userId: 245,
    salary: 37855,
    yearsOfExperience: 15,
  },
  {
    id: 246,
    jobFunctionId: 3,
    seniorityId: 2,
    industryId: 4,
    genderId: 1,
    userId: 246,
    salary: 66671,
    yearsOfExperience: 20,
  },
  {
    id: 247,
    jobFunctionId: 1,
    seniorityId: 4,
    industryId: 1,
    genderId: 1,
    userId: 247,
    salary: 93916,
    yearsOfExperience: 14,
  },
  {
    id: 248,
    jobFunctionId: 4,
    seniorityId: 3,
    industryId: 4,
    genderId: 1,
    userId: 248,
    salary: 103923,
    yearsOfExperience: 4,
  },
  {
    id: 249,
    jobFunctionId: 2,
    seniorityId: 2,
    industryId: 4,
    genderId: 1,
    userId: 249,
    salary: 56692,
    yearsOfExperience: 16,
  },
  {
    id: 250,
    jobFunctionId: 1,
    seniorityId: 2,
    industryId: 5,
    genderId: 1,
    userId: 250,
    salary: 46639,
    yearsOfExperience: 7,
  },
];
