export type BarGraphProps = {
  foodDelivery: number;
  techAvg: number;
  consultAvg: number;
  pharmaAvg: number;
  financeAvg: number;
  healthAvg: number;
  user: string;
  jobdetails: { salary: number; jobFunction: string }[];
  maleSalAvg: number;
  femaleSalAvg: number;
  salaryAvgMarket: number;
  minValueMArket: number;
  maxValueMArket: number;
  salaryAvgJunior: number;
  salaryAvgMid: number;
  salaryAvgSenior: number;
  salaryAvgPrincple: number;
  salaryAvgLead: number;
  salaryAvgJuniorMale: number;
  salaryAvgMidMale: number;
  salaryAvgSeniorMale: number;
  salaryAvgPrincpleMale: number;
  salaryAvgLeadMale: number;
  salaryAvgJuniorFemale: number;
  salaryAvgMidFemale: number;
  salaryAvgSeniorFemale: number;
  salaryAvgPrincpleFemale: number;
  salaryAvgLeadFemale: number;
  jobDetailsLevel: string;
  jobDetailstitle: string;
  jobDetailsSalary: number;
  ratioMaleGender: number;
  ratioFemGender: number;
};
